<?php

// TODO refactor

namespace console\models\start;

use common\components\helpers\ErrorHelper;
use common\models\db\City;
use common\models\db\Country;
use common\models\db\Stadium;
use common\models\db\Team;
use Exception;
use Yii;

/**
 * Class InsertTeam
 * @package console\models\start
 */
class InsertTeam
{
    /**
     * @return void
     * @throws Exception
     */
    public function execute()
    {
        $teamArray = [
            [
                'country' => 'England',
                'list' => [
                    ['team' => 'Bath', 'stadium' => 'Recreation Ground', 'city' => 'Bath'],
                    ['team' => 'Bristol Bears', 'stadium' => 'Ashton Gate', 'city' => 'Bristol'],
                    ['team' => 'Exeter Chiefs', 'stadium' => 'Sandy', 'city' => 'Exeter'],
                    ['team' => 'Gloucester', 'stadium' => 'Kingsholm', 'city' => 'Gloucester'],
                    ['team' => 'Harlequins', 'stadium' => 'Twickenham Stoop', 'city' => 'London'],
                    ['team' => 'Leicester Tigers', 'stadium' => 'Welford', 'city' => 'Leicester'],
                    ['team' => 'London Irish', 'stadium' => 'Madejski', 'city' => 'Reading'],
                    ['team' => 'Northampton Saints', 'stadium' => 'Franklin\'s Gardens', 'city' => 'Northampton'],
                    ['team' => 'Sale Sharks', 'stadium' => 'AJ Bell', 'city' => 'Salford'],
                    ['team' => 'Saracens', 'stadium' => 'Allianz', 'city' => 'London'],
                    ['team' => 'Wasps', 'stadium' => 'Ricoh', 'city' => 'Coventry'],
                    ['team' => 'Worcester Warriors', 'stadium' => 'Sixways', 'city' => 'Worcester'],
                    ['team' => 'Ampthill', 'stadium' => 'Dillingham', 'city' => 'Ampthill'],
                    ['team' => 'Bedford Blues', 'stadium' => 'Goldington', 'city' => 'Bedford'],
                    ['team' => 'Cornish Pirates', 'stadium' => 'Mennaye Field', 'city' => 'Penzance'],
                    ['team' => 'Coventry', 'stadium' => 'Butts', 'city' => 'Coventry'],
                    ['team' => 'Doncaster Knights', 'stadium' => 'Castle', 'city' => 'Doncaster'],
                    ['team' => 'Ealing Trailfinders', 'stadium' => 'Trailfinders', 'city' => 'West Ealing'],
                    ['team' => 'Hartpury College', 'stadium' => 'Gillman', 'city' => 'Hartpury'],
                    ['team' => 'Jersey Reds', 'stadium' => 'Santander', 'city' => 'Saint Peter'],
                    ['team' => 'London Scottish', 'stadium' => 'Athletic', 'city' => 'Richmond'],
                    ['team' => 'Newcastle Falcons', 'stadium' => 'Kingston', 'city' => 'Newcastle'],
                    ['team' => 'Nottingham', 'stadium' => 'Lady Bay', 'city' => 'Nottingham'],
                    ['team' => 'Yorkshire Carnegie', 'stadium' => 'Headingley Carnegie', 'city' => 'Leeds'],
                    ['team' => 'Birmingham Moseley', 'stadium' => 'Billesley Common', 'city' => 'Birmingham'],
                    ['team' => 'Bishop\'s Stortford', 'stadium' => 'Silver Leys', 'city' => 'Bishop\'s Stortford'],
                    ['team' => 'Blackheath', 'stadium' => 'Well Hall', 'city' => 'Eltham'],
                    ['team' => 'Cambridge', 'stadium' => 'Grantchester', 'city' => 'Cambridge'],
                    ['team' => 'Canterbury', 'stadium' => 'Marine Travel', 'city' => 'Canterbury'],
                    ['team' => 'Chinnor', 'stadium' => 'Kingsey', 'city' => 'Thame'],
                    ['team' => 'Cinderford', 'stadium' => 'Dockham', 'city' => 'Cinderford'],
                    ['team' => 'Darlington Mowden', 'stadium' => 'Northern Echo', 'city' => 'Darlington'],
                    ['team' => 'Hull Ionians', 'stadium' => 'Brantingham', 'city' => 'Brantingham'],
                    ['team' => 'Rams', 'stadium' => 'Old Bath', 'city' => 'Sonning'],
                ],
            ],
            [
                'country' => 'Ireland',
                'list' => [
                    ['team' => 'Ulster', 'stadium' => 'Ravenhill', 'city' => 'Belfast'],
                    ['team' => 'Munster', 'stadium' => 'Thomond', 'city' => 'Limerick Cork'],
                    ['team' => 'Leinster', 'stadium' => 'RDS', 'city' => 'Dublin'],
                    ['team' => 'Connacht', 'stadium' => 'Galway', 'city' => 'Galway'],
                    ['team' => 'Ballynahinch', 'stadium' => 'Ballymacarn', 'city' => 'Down'],
                    ['team' => 'Clontarf', 'stadium' => 'Castle Avenue', 'city' => 'Dublin'],
                    ['team' => 'Cork Constitution', 'stadium' => 'Temple Hill', 'city' => 'Cork'],
                    ['team' => 'Dublin University', 'stadium' => 'College', 'city' => 'Dublin'],
                    ['team' => 'Garryowen', 'stadium' => 'Dooradoyle', 'city' => 'Limerick'],
                    ['team' => 'Lansdowne', 'stadium' => 'Aviva', 'city' => 'Dublin'],
                    ['team' => 'Terenure College', 'stadium' => 'Lakelands', 'city' => 'Dublin'],
                    ['team' => 'UCC', 'stadium' => 'Mardyke', 'city' => 'Cork'],
                    ['team' => 'UCD', 'stadium' => 'UCD Bowl', 'city' => 'Dublin'],
                    ['team' => 'Young Munster', 'stadium' => 'Tom Clifford', 'city' => 'Limerick'],
                    ['team' => 'Armagh', 'stadium' => 'Palace Grounds', 'city' => 'Armagh'],
                    ['team' => 'Banbridge', 'stadium' => 'Rifle', 'city' => 'Banbridge'],
                    ['team' => 'Highfield', 'stadium' => 'Woodleigh', 'city' => 'Cork'],
                    ['team' => 'Malone', 'stadium' => 'Gibson', 'city' => 'Belfast'],
                    ['team' => 'Naas', 'stadium' => 'Forenaughts', 'city' => 'Naas'],
                    ['team' => 'Navan', 'stadium' => 'Balreask Old', 'city' => 'Navan'],
                    ['team' => 'Old Belvedere', 'stadium' => 'Anglesea', 'city' => 'Dublin'],
                    ['team' => 'Old Wesley', 'stadium' => 'Donnybrook', 'city' => 'Dublin'],
                    ['team' => 'Shannon', 'stadium' => 'Thomond', 'city' => 'Limerick'],
                    ['team' => 'St Mary\'s College', 'stadium' => 'Templeville', 'city' => 'Dublin'],
                    ['team' => 'Ballymena', 'stadium' => 'Eaton', 'city' => 'Antrim'],
                    ['team' => 'Buccaneers', 'stadium' => 'Dubarry', 'city' => 'Athlone'],
                    ['team' => 'Cashel', 'stadium' => 'Spafield', 'city' => 'Cashel'],
                    ['team' => 'Dolphin', 'stadium' => 'Musgrave', 'city' => 'Cork'],
                    ['team' => 'MU Barnhall', 'stadium' => 'Parsonstown', 'city' => 'Leixlip'],
                    ['team' => 'Nenagh Ormond', 'stadium' => 'New Ormond', 'city' => 'Nenagh'],
                    ['team' => 'Old Crescent', 'stadium' => 'Rosbrien', 'city' => 'Limerick'],
                    ['team' => 'Queen\'s University', 'stadium' => 'Dub Lane', 'city' => 'Belfast'],
                    ['team' => 'Rainey Old Boys', 'stadium' => 'Hatrick', 'city' => 'Magherafelt'],
                    ['team' => 'UL Bohemians', 'stadium' => 'Annacotty', 'city' => 'Limerick'],
                ],
            ],
            [
                'country' => 'Scotland',
                'list' => [
                    ['team' => 'Edinburgh', 'stadium' => 'Murrayfield', 'city' => 'Edinburgh'],
                    ['team' => 'Glasgow Warriors', 'stadium' => 'Scotstoun', 'city' => 'Glasgow'],
                    ['team' => 'Ayrshire Bulls', 'stadium' => 'Millbrae', 'city' => 'Ayr'],
                    ['team' => 'Boroughmuir', 'stadium' => 'Meggetland', 'city' => 'Edinburgh'],
                    ['team' => 'Heriot\'s', 'stadium' => 'Goldenacre', 'city' => 'Edinburgh'],
                    ['team' => 'Southern Knights', 'stadium' => 'Greenyards', 'city' => 'Melrose'],
                    ['team' => 'Stirling County', 'stadium' => 'Bridgehaugh', 'city' => 'Stirling'],
                    ['team' => 'Watsonian', 'stadium' => 'Myreside', 'city' => 'Edinburgh'],
                    ['team' => 'Aberdeen GSFP', 'stadium' => 'Rubislaw', 'city' => 'Aberdeen'],
                    ['team' => 'Currie', 'stadium' => 'Malleny', 'city' => 'Balerno'],
                    ['team' => 'Edinburgh Academicals', 'stadium' => 'Raeburn', 'city' => 'Edinburgh'],
                    ['team' => 'Glasgow Hawks', 'stadium' => 'Balgray', 'city' => 'Glasgow'],
                    ['team' => 'Glasgow Hutchesons Aloysians', 'stadium' => 'Braidholm', 'city' => 'Giffnock'],
                    ['team' => 'Hawick', 'stadium' => 'Mansfield', 'city' => 'Hawick'],
                    ['team' => 'Jed-Forest', 'stadium' => 'Riverside', 'city' => 'Jedburgh'],
                    ['team' => 'Marr', 'stadium' => 'Fullerton', 'city' => 'Troon'],
                    ['team' => 'Musselburgh', 'stadium' => 'Stoneyhill', 'city' => 'Musselburgh'],
                    ['team' => 'Selkirk', 'stadium' => 'Philiphaugh', 'city' => 'Selkirk'],
                    ['team' => 'Biggar', 'stadium' => 'Hartree Mill', 'city' => 'Biggar'],
                    ['team' => 'Heriots', 'stadium' => 'Heriots', 'city' => 'Edinburgh'],
                    ['team' => 'Highland', 'stadium' => 'Canal', 'city' => 'Inverness'],
                    ['team' => 'Melrose', 'stadium' => 'Greenyards', 'city' => 'Melrose'],
                    ['team' => 'Gala', 'stadium' => 'Netherdale', 'city' => 'Galashiels'],
                    ['team' => 'Stirling County', 'stadium' => 'Bridgehaugh', 'city' => 'Stirling'],
                    ['team' => 'Watsonians', 'stadium' => 'New Myreside', 'city' => 'Edinburgh'],
                    ['team' => 'Cartha Queens Park', 'stadium' => 'Dumbreck', 'city' => 'Glasgow'],
                    ['team' => 'Kelso', 'stadium' => 'Poynder', 'city' => 'Kelso'],
                    ['team' => 'Ayr', 'stadium' => 'Millbrae', 'city' => 'Ayr'],
                    ['team' => 'Boroughmuir', 'stadium' => 'Meggetland', 'city' => 'Edinburgh'],
                    ['team' => 'Dundee', 'stadium' => 'Mayfield', 'city' => 'Dundee'],
                    ['team' => 'Dumfries Saints', 'stadium' => 'Farm', 'city' => 'Dumfries'],
                    ['team' => 'Falkirk', 'stadium' => 'Horne', 'city' => 'Falkirk'],
                    ['team' => 'Gordonians', 'stadium' => 'Countesswells', 'city' => 'Aberdeen'],
                    ['team' => 'Kirkcaldy', 'stadium' => 'Beveridge', 'city' => 'Kirkcaldy'],
                ],
            ],
            [
                'country' => 'Wales',
                'list' => [
                    ['team' => 'Cardiff Blues', 'stadium' => 'Cardiff Arms', 'city' => 'Cardiff'],
                    ['team' => 'Dragons', 'stadium' => 'Rodney Parade', 'city' => 'Newport'],
                    ['team' => 'Ospreys', 'stadium' => 'Liberty', 'city' => 'Swansea'],
                    ['team' => 'Scarlets', 'stadium' => 'Scarlets', 'city' => 'Llanelli'],
                    ['team' => 'Cardiff', 'stadium' => 'Cardiff Arms', 'city' => 'Cardiff'],
                    ['team' => 'Carmarthen Quins', 'stadium' => 'Carmarthen', 'city' => 'Carmarthen'],
                    ['team' => 'Aberavon', 'stadium' => 'Talbot Athletic', 'city' => 'Port Talbot'],
                    ['team' => 'Llandovery', 'stadium' => 'Church Bank', 'city' => 'Llandovery'],
                    ['team' => 'Pontypridd', 'stadium' => 'Sardis', 'city' => 'Pontypridd'],
                    ['team' => 'Merthyr', 'stadium' => 'Wern', 'city' => 'Merthyr Tydfil'],
                    ['team' => 'RGC 1404', 'stadium' => 'Eirias', 'city' => 'Colwyn Bay'],
                    ['team' => 'Newport', 'stadium' => 'Rodney Parade', 'city' => 'Newport'],
                    ['team' => 'Swansea', 'stadium' => 'St Helen\'s', 'city' => 'Swansea'],
                    ['team' => 'Llanelli', 'stadium' => 'Scarlets', 'city' => 'Llanelli'],
                    ['team' => 'Ebbw Vale', 'stadium' => 'Eugene Cross', 'city' => 'Ebbw Vale'],
                    ['team' => 'Bridgend Ravens', 'stadium' => 'Morganstone Brewery', 'city' => 'Bridgend'],
                    ['team' => 'Pontypool', 'stadium' => 'Pontypool', 'city' => 'Pontypool'],
                    ['team' => 'Ystrad Rhondda', 'stadium' => 'Gelligaled', 'city' => 'Ystrad Rhondda'],
                    ['team' => 'Narberth', 'stadium' => 'Lewis Lloyd', 'city' => 'Narberth'],
                    ['team' => 'Cardiff MU', 'stadium' => 'Cyncoed Campus', 'city' => 'Cardiff'],
                    ['team' => 'Bedlinog', 'stadium' => 'Rec', 'city' => 'Bedlinog'],
                    ['team' => 'Maesteg Harlequins', 'stadium' => 'South Parade', 'city' => 'Maesteg'],
                    ['team' => 'Trebanos', 'stadium' => 'Park', 'city' => 'Trebanos'],
                    ['team' => 'Newbridge', 'stadium' => 'Welfare', 'city' => 'Newbridge'],
                    ['team' => 'Tata Steel', 'stadium' => 'Margam', 'city' => 'Port Talbot'],
                    ['team' => 'Beddau', 'stadium' => 'Mount Pleasant', 'city' => 'Beddau'],
                    ['team' => 'Rhydyfelin', 'stadium' => 'Rec', 'city' => 'Rhydyfelin'],
                    ['team' => 'Newcastle Emlyn', 'stadium' => 'Dol Wiber', 'city' => 'Newcastle Emlyn'],
                    ['team' => 'Brecon', 'stadium' => 'Pugh', 'city' => 'Brecon'],
                    ['team' => 'Brynmawr', 'stadium' => 'Rec', 'city' => 'Brynmawr'],
                    ['team' => 'Penallta', 'stadium' => 'Ystrad Fawr', 'city' => 'Ystrad Mynach'],
                    ['team' => 'Glynneath', 'stadium' => 'Abernant', 'city' => 'Glynneath'],
                    ['team' => 'Tondu', 'stadium' => 'Pandy', 'city' => 'Aberkenfig'],
                    ['team' => 'Tonmawr', 'stadium' => 'Whitworth', 'city' => 'Tonmawr'],
                ],
            ],
            [
                'country' => 'Australia',
                'list' => [
                    ['team' => 'Brumbies', 'stadium' => 'Canberra', 'city' => 'Canberra'],
                    ['team' => 'Melbourne Rebels', 'stadium' => 'Melbourne', 'city' => 'Melbourne'],
                    ['team' => 'NSW Waratahs', 'stadium' => 'Sydney', 'city' => 'Sydney'],
                    ['team' => 'Queensland Reds', 'stadium' => 'Ballymore', 'city' => 'Brisbane'],
                    ['team' => 'Brisbane City', 'stadium' => 'Ballymore', 'city' => 'Brisbane'],
                    ['team' => 'Canberra Vikings', 'stadium' => 'Viking', 'city' => 'Canberra'],
                    ['team' => 'NSWC Eagles', 'stadium' => 'Caltex', 'city' => 'Dubbo'],
                    ['team' => 'Melbourne Rising', 'stadium' => 'Casey Fields', 'city' => 'Melbourne'],
                    ['team' => 'Queensland Country', 'stadium' => 'Bond Sports', 'city' => 'Robina'],
                    ['team' => 'Sydney', 'stadium' => 'Woollahra Oval', 'city' => 'Sydney'],
                    ['team' => 'Western Force', 'stadium' => 'HBF', 'city' => 'Perth'],
                    ['team' => 'Melbourne', 'stadium' => 'Melbourne', 'city' => 'Melbourne'],
                    ['team' => 'Adelaide', 'stadium' => 'Adelaide', 'city' => 'Adelaide'],
                    ['team' => 'Gold Coast', 'stadium' => 'Gold Coast', 'city' => 'Gold Coast'],
                    ['team' => 'Tweed Heads', 'stadium' => 'Tweed Heads', 'city' => 'Tweed Heads'],
                    ['team' => 'Newcastle', 'stadium' => 'Newcastle', 'city' => 'Newcastle'],
                    ['team' => 'Maitland', 'stadium' => 'Maitland', 'city' => 'Maitland'],
                    ['team' => 'Queanbeyan', 'stadium' => 'Queanbeyan', 'city' => 'Queanbeyan'],
                    ['team' => 'Sunshine Coast', 'stadium' => 'Sunshine Coast', 'city' => 'Sunshine Coast'],
                    ['team' => 'Wollongong', 'stadium' => 'Wollongong', 'city' => 'Wollongong'],
                    ['team' => 'Geelong', 'stadium' => 'Geelong', 'city' => 'Geelong'],
                    ['team' => 'Hobart', 'stadium' => 'Hobart', 'city' => 'Hobart'],
                    ['team' => 'Townsville', 'stadium' => 'Townsville', 'city' => 'Townsville'],
                    ['team' => 'Cairns', 'stadium' => 'Cairns', 'city' => 'Cairns'],
                    ['team' => 'Darwin', 'stadium' => 'Darwin', 'city' => 'Darwin'],
                    ['team' => 'Toowoomba', 'stadium' => 'Toowoomba', 'city' => 'Toowoomba'],
                    ['team' => 'Ballarat', 'stadium' => 'Ballarat', 'city' => 'Ballarat'],
                    ['team' => 'Bendigo', 'stadium' => 'Bendigo', 'city' => 'Bendigo'],
                    ['team' => 'Albury', 'stadium' => 'Albury', 'city' => 'Albury'],
                    ['team' => 'Wodonga', 'stadium' => 'Wodonga', 'city' => 'Wodonga'],
                    ['team' => 'Launceston', 'stadium' => 'Launceston', 'city' => 'Launceston'],
                    ['team' => 'Mackay', 'stadium' => 'Mackay', 'city' => 'Mackay'],
                    ['team' => 'Rockhampton', 'stadium' => 'Rockhampton', 'city' => 'Rockhampton'],
                    ['team' => 'Bunbury', 'stadium' => 'Bunbury', 'city' => 'Bunbury'],
                ],
            ],
            [
                'country' => 'Argentina',
                'list' => [
                    ['team' => 'Ceibos', 'stadium' => 'Tala', 'city' => 'Cardoba'],
                    ['team' => 'Jaguares', 'stadium' => 'Jose Amalfitani', 'city' => 'Buenos Aires'],
                    ['team' => 'San Isidro', 'stadium' => 'Boulogne', 'city' => 'Boulogne'],
                    ['team' => 'CASI', 'stadium' => 'San Isidro', 'city' => 'San Isidro'],
                    ['team' => 'San Luis', 'stadium' => 'La Plata', 'city' => 'La Plata'],
                    ['team' => 'Duendes', 'stadium' => 'Las Delicias', 'city' => 'Rosario'],
                    ['team' => 'Natacion y Gimnasia', 'stadium' => 'Gabriel Palou', 'city' => 'San Miguel de Tucuman'],
                    ['team' => 'Los Tarcos', 'stadium' => 'Brigido', 'city' => 'San Miguel de Tucuman'],
                    ['team' => 'Belgrano', 'stadium' => 'Virrey del Pino 3456', 'city' => 'Belgrano'],
                    ['team' => 'Jockey Rosario', 'stadium' => 'Rosario', 'city' => 'Rosario'],
                    ['team' => 'Tucuman', 'stadium' => 'Marcos Paz', 'city' => 'San Miguel de Tucuman'],
                    ['team' => 'Regatas', 'stadium' => 'Francia', 'city' => 'Bella Vista'],
                    ['team' => 'Uru Cure', 'stadium' => 'Uru Cure', 'city' => 'Los Tordos'],
                    ['team' => 'Universitario', 'stadium' => 'Villa de Mayo', 'city' => 'Buenos Aires'],
                    ['team' => 'Hindu', 'stadium' => 'Del Golf', 'city' => 'Don Torcuato'],
                    ['team' => 'La Plata', 'stadium' => 'El Bosque', 'city' => 'Manuel B. Gonnet'],
                    ['team' => 'Alumni', 'stadium' => 'Tortuguitas', 'city' => 'Tortuguitas'],
                    ['team' => 'Marista', 'stadium' => 'La Carrodilla', 'city' => 'Mendoza'],
                    ['team' => 'Tucuman LT', 'stadium' => 'El Salvador', 'city' => 'San Miguel de Tucuman'],
                    ['team' => 'Jockey Cordoba', 'stadium' => 'Unión Cordobesa', 'city' => 'Córdoba'],
                    ['team' => 'GER', 'stadium' => 'GER', 'city' => 'Rosario'],
                    ['team' => 'Cordoba Atletico', 'stadium' => 'Presidente Peron', 'city' => 'Cordoba'],
                    ['team' => 'Pucara', 'stadium' => 'Burzaco', 'city' => 'Burzaco'],
                    ['team' => 'Newman', 'stadium' => 'Brother Timothy O\'Brien', 'city' => 'Benavidez'],
                    ['team' => 'Mar del Plata', 'stadium' => 'Mar del Plata', 'city' => 'Mar del Plata'],
                    ['team' => 'Atletico del Rosario', 'stadium' => 'Plaza Jewell', 'city' => 'Rosario'],
                    ['team' => 'Los Tilos', 'stadium' => 'Barrio Obrero', 'city' => 'La Plata'],
                    ['team' => 'Buenos Aires', 'stadium' => 'San Fernando', 'city' => 'San Fernando'],
                    ['team' => 'Gimnasia y Esgrima', 'stadium' => 'G.E.B.A.', 'city' => 'Buenos Aires'],
                    ['team' => 'Salta', 'stadium' => 'Salta', 'city' => 'Salta'],
                    ['team' => 'Vicente Lopez', 'stadium' => 'Vicente Lopez', 'city' => 'Vicente Lopez'],
                    ['team' => 'Corrientes', 'stadium' => 'Corrientes', 'city' => 'Corrientes'],
                    ['team' => 'Pilar', 'stadium' => 'Pilar', 'city' => 'Pilar'],
                    ['team' => 'Resistencia', 'stadium' => 'Resistencia', 'city' => 'Resistencia'],
                ],
            ],
            [
                'country' => 'France',
                'list' => [
                    ['team' => 'Sporting Union Agen', 'stadium' => 'Armandie', 'city' => 'Agen'],
                    ['team' => 'Aviron Bayonnais', 'stadium' => 'Jean Dauger', 'city' => 'Bayonne'],
                    ['team' => 'Union Bordeaux Bègles', 'stadium' => 'Chaban-Delmas', 'city' => 'Bordeaux'],
                    ['team' => 'Athletique Brive', 'stadium' => 'Amedee-Domenech', 'city' => 'Brive-la-Gaillarde'],
                    ['team' => 'Castres Olympique', 'stadium' => 'Pierre-Fabre', 'city' => 'Castres'],
                    ['team' => 'ASM Clermont Auvergne', 'stadium' => 'Marcel Michelin', 'city' => 'Clermont-Ferrand'],
                    ['team' => 'Stade Rochelais', 'stadium' => 'Marcel-Deflandre', 'city' => 'La Rochelle'],
                    ['team' => 'Lyon Olympique Universitaire', 'stadium' => 'Gerland', 'city' => 'Lyon'],
                    ['team' => 'Montpellier Hérault', 'stadium' => 'Altrad', 'city' => 'Montpellier'],
                    ['team' => 'Section Paloise', 'stadium' => 'Hameau', 'city' => 'Pau'],
                    ['team' => 'Racing 92', 'stadium' => 'Paris La Defense', 'city' => 'Nanterre'],
                    ['team' => 'Stade Francais', 'stadium' => 'Jean-Bouin', 'city' => 'Paris'],
                    ['team' => 'RC Toulonnais', 'stadium' => 'Mayol', 'city' => 'Toulon'],
                    ['team' => 'Toulouse', 'stadium' => 'Ernest-Wallon', 'city' => 'Toulouse'],
                    ['team' => 'Aurillac', 'stadium' => 'Jean Alric', 'city' => 'Aurillac'],
                    ['team' => 'Beziers', 'stadium' => 'Mediterranée', 'city' => 'Beziers'],
                    ['team' => 'Biarritz', 'stadium' => 'Sports Aguiléra', 'city' => 'Biarritz'],
                    ['team' => 'Carcassonne', 'stadium' => 'Albert Domec', 'city' => 'Carcassonne'],
                    ['team' => 'Colomiers', 'stadium' => 'Michel Bendichou', 'city' => 'Colomiers'],
                    ['team' => 'Grenoble', 'stadium' => 'Alpes', 'city' => 'Grenoble'],
                    ['team' => 'Mont-de-Marsan', 'stadium' => 'Guy Boniface', 'city' => 'Mont-de-Marsan'],
                    ['team' => 'Montauban', 'stadium' => 'Sapiac', 'city' => 'Montauban'],
                    ['team' => 'Nevers', 'stadium' => 'Pre Fleuri', 'city' => 'Nevers'],
                    ['team' => 'Oyonnax', 'stadium' => 'Charles-Mathon', 'city' => 'Oyonnax'],
                    ['team' => 'Perpignan', 'stadium' => 'Aime Giral', 'city' => 'Perpignan'],
                    ['team' => 'Provence', 'stadium' => 'Maurice David', 'city' => 'Aix-en-Provence'],
                    ['team' => 'Rouen', 'stadium' => 'Jean-Mermoz', 'city' => 'Rouen'],
                    ['team' => 'Soyaux Angouleme', 'stadium' => 'Chanzy', 'city' => 'Angouleme'],
                    ['team' => 'Valence Romans', 'stadium' => 'Marcel Guillermoz', 'city' => 'Romans-sur-Isere'],
                    ['team' => 'Vannes', 'stadium' => 'Rabine', 'city' => 'Vannes'],
                    ['team' => 'Rumilly', 'stadium' => 'Grangettes', 'city' => 'Rumilly'],
                    ['team' => 'Nice', 'stadium' => 'Nicois', 'city' => 'Nice'],
                    ['team' => 'Graulhet', 'stadium' => 'Noel', 'city' => 'Graulhet'],
                    ['team' => 'Bourgoin-Jallieu', 'stadium' => 'Pierre Rajon', 'city' => 'Bourgoin-Jallieu'],
                ],
            ],
            [
                'country' => 'Italy',
                'list' => [
                    ['team' => 'Benetton', 'stadium' => 'Monigo', 'city' => 'Treviso'],
                    ['team' => 'Zebre', 'stadium' => 'Sergio Lanfranchi	', 'city' => 'Parma'],
                    ['team' => 'San Dona', 'stadium' => 'Romolo Pacifici', 'city' => 'San Dona'],
                    ['team' => 'Calvisano', 'stadium' => 'San Michele', 'city' => 'Calvisano'],
                    ['team' => 'Colorno', 'stadium' => 'Gino Maini', 'city' => 'Colorno'],
                    ['team' => 'Fiamme Oro', 'stadium' => 'Polizia di Stato', 'city' => 'Rome'],
                    ['team' => 'S.S. Lazio', 'stadium' => 'Giulio Onesti', 'city' => 'Rome'],
                    ['team' => 'I Medicei', 'stadium' => 'Mario Lodigiani', 'city' => 'Florence'],
                    ['team' => 'Lyons Piacenza', 'stadium' => 'Beltrametti', 'city' => 'Piacenza'],
                    ['team' => 'Mogliano', 'stadium' => 'Maurizio Quaggia', 'city' => 'Mogliano'],
                    ['team' => 'Petrarca', 'stadium' => 'Plebiscito', 'city' => 'Padua'],
                    ['team' => 'Rovigo Delta', 'stadium' => 'Mario Battaglini', 'city' => 'Rovigo'],
                    ['team' => 'Valorugby Emilia', 'stadium' => 'Mirabello', 'city' => 'Reggio nell\'Emilia'],
                    ['team' => 'Viadana', 'stadium' => 'Luigi Zaffanella', 'city' => 'Viadana'],
                    ['team' => 'Accademia Francescato', 'stadium' => 'Ivan Francescato', 'city' => 'Parma'],
                    ['team' => 'As Milano', 'stadium' => 'Milano', 'city' => 'Milan'],
                    ['team' => 'Recco', 'stadium' => 'Recco', 'city' => 'Recco'],
                    ['team' => 'Cus Torino', 'stadium' => 'Torino', 'city' => 'Turin'],
                    ['team' => 'Parabiago', 'stadium' => 'Parabiago', 'city' => 'Parabiago'],
                    ['team' => 'Genova', 'stadium' => 'Genova', 'city' => 'Genoa'],
                    ['team' => 'Biella', 'stadium' => 'Biella', 'city' => 'Biella'],
                    ['team' => 'VII Torino', 'stadium' => 'Torino', 'city' => 'Turin'],
                    ['team' => 'Cus Milano', 'stadium' => 'Milano', 'city' => 'Milan'],
                    ['team' => 'Noceto', 'stadium' => 'Noceto', 'city' => 'Noceto'],
                    ['team' => 'Ruggers Tarvisium', 'stadium' => 'San Paolo', 'city' => 'Treviso'],
                    ['team' => 'Petrarca Cadetta', 'stadium' => 'Memo Geremia', 'city' => 'Padova'],
                    ['team' => 'Valpolicella', 'stadium' => 'Valpolicella', 'city' => 'Valpolicella'],
                    ['team' => 'Paese', 'stadium' => 'Paese', 'city' => 'Paese'],
                    ['team' => 'Badia', 'stadium' => 'Badia', 'city' => 'Badia Polesine'],
                    ['team' => 'Udine', 'stadium' => 'Udine', 'city' => 'Udine'],
                    ['team' => 'Vicenza', 'stadium' => 'Vicenza', 'city' => 'Vicenza'],
                    ['team' => 'Brescia', 'stadium' => 'Brescia', 'city' => 'Brescia'],
                    ['team' => 'Capitolina', 'stadium' => 'Unione', 'city' => 'Rome'],
                    ['team' => 'Catania', 'stadium' => 'Santa Maria Goretti', 'city' => 'Catania'],
                ],
            ],
            [
                'country' => 'New Zealand',
                'list' => [
                    ['team' => 'Blues', 'stadium' => 'Eden', 'city' => 'Auckland'],
                    ['team' => 'Chiefs', 'stadium' => 'Waikato', 'city' => 'Hamilton'],
                    ['team' => 'Crusaders', 'stadium' => 'Rugby League', 'city' => 'Christchurch'],
                    ['team' => 'Highlanders', 'stadium' => 'Forsyth Barr', 'city' => 'Dunedin'],
                    ['team' => 'Hurricanes', 'stadium' => 'Westpac', 'city' => 'Wellington'],
                    ['team' => 'Auckland', 'stadium' => 'Eden', 'city' => 'Auckland'],
                    ['team' => 'Canterbury', 'stadium' => 'AMI', 'city' => 'Christchurch'],
                    ['team' => 'Counties Manukau', 'stadium' => 'ECOLight', 'city' => 'Pukekohe'],
                    ['team' => 'North Harbour', 'stadium' => 'QBE', 'city' => 'Auckland'],
                    ['team' => 'Tasman', 'stadium' => 'Trafalgar', 'city' => 'Nelson'],
                    ['team' => 'Waikato', 'stadium' => 'Waikato', 'city' => 'Hamilton'],
                    ['team' => 'Wellington', 'stadium' => 'Westpac', 'city' => 'Wellington'],
                    ['team' => 'Bay of Plenty', 'stadium' => 'Rotorua', 'city' => 'Mount Maunganui'],
                    ['team' => 'Hawke\'s Bay', 'stadium' => 'McLean', 'city' => 'Napier'],
                    ['team' => 'Manawatu', 'stadium' => 'Energy Trust', 'city' => 'Palmerston North'],
                    ['team' => 'Northland', 'stadium' => 'Toll', 'city' => 'Whangarei'],
                    ['team' => 'Otago', 'stadium' => 'Forsyth Barr', 'city' => 'Dunedin'],
                    ['team' => 'Southland', 'stadium' => 'Forsyth Barr', 'city' => 'Invercargill'],
                    ['team' => 'Taranaki', 'stadium' => 'Yarrow', 'city' => 'New Plymouth'],
                    ['team' => 'Buller', 'stadium' => 'Victoria Square', 'city' => 'Westport'],
                    ['team' => 'East Coast', 'stadium' => 'Whakarua', 'city' => 'Ruatoria'],
                    ['team' => 'Horowhenua-Kapiti', 'stadium' => 'Levin Domain', 'city' => 'Levin'],
                    ['team' => 'King Country', 'stadium' => 'Owen Delany', 'city' => 'Taupo'],
                    ['team' => 'Mid Canterbury', 'stadium' => 'Ashburton', 'city' => 'Ashburton'],
                    ['team' => 'North Otago', 'stadium' => 'Whitestone', 'city' => 'Oamaru'],
                    ['team' => 'Poverty Bay', 'stadium' => 'More FM Rugby', 'city' => 'Gisborne'],
                    ['team' => 'South Canterbury', 'stadium' => 'Alpine Energy', 'city' => 'Timaru'],
                    ['team' => 'Thames Valley', 'stadium' => 'Paeroa Domain', 'city' => 'Paeroa'],
                    ['team' => 'Wairarapa Bush', 'stadium' => 'Memorial', 'city' => 'Masterton'],
                    ['team' => 'Wanganui', 'stadium' => 'Cooks Gardens', 'city' => 'Whanganui'],
                    ['team' => 'West Coast', 'stadium' => 'Rugby', 'city' => 'Greymouth'],
                    ['team' => 'Tauranga', 'stadium' => 'Tauranga', 'city' => 'Tauranga'],
                    ['team' => 'Lower Hutt', 'stadium' => 'Lower Hutt', 'city' => 'Lower Hutt'],
                    ['team' => 'Upper Hutt', 'stadium' => 'Upper Hutt', 'city' => 'Upper Hutt'],
                ],
            ],
            [
                'country' => 'South Africa',
                'list' => [
                    ['team' => 'Bulls', 'stadium' => 'Loftus Versfeld', 'city' => 'Pretoria'],
                    ['team' => 'Lions', 'stadium' => 'Emirates Airline', 'city' => 'Johannesburg'],
                    ['team' => 'Sharks', 'stadium' => 'Kings Park', 'city' => 'Durban'],
                    ['team' => 'Stormers', 'stadium' => 'Newlands', 'city' => 'Cape Town'],
                    ['team' => 'Cheetahs', 'stadium' => 'Free State', 'city' => 'Bloemfontein'],
                    ['team' => 'Southern Kings', 'stadium' => 'Nelson Mandela Bay', 'city' => 'Port Elizabeth'],
                    ['team' => 'Blue Bulls', 'stadium' => 'Pretoria', 'city' => 'Pretoria'],
                    ['team' => 'Boland Cavaliers', 'stadium' => 'Wellington', 'city' => 'Wellington'],
                    ['team' => 'Border Bulldogs', 'stadium' => 'East London', 'city' => 'East London'],
                    ['team' => 'Eastern Province Kings', 'stadium' => 'Port Elizabeth', 'city' => 'Port Elizabeth'],
                    ['team' => 'Falcons', 'stadium' => 'Kempton Park', 'city' => 'Kempton Park'],
                    ['team' => 'Free State Cheetahs', 'stadium' => 'Bloemfontein', 'city' => 'Bloemfontein'],
                    ['team' => 'Golden Lions', 'stadium' => 'Johannesburg', 'city' => 'Johannesburg'],
                    ['team' => 'Griffons', 'stadium' => 'Welkom', 'city' => 'Welkom'],
                    ['team' => 'Griquas', 'stadium' => 'Kimberley', 'city' => 'Kimberley'],
                    ['team' => 'Leopards', 'stadium' => 'Potchefstroom', 'city' => 'Potchefstroom'],
                    ['team' => 'Pumas', 'stadium' => 'Mbombela', 'city' => 'Mbombela'],
                    ['team' => 'Sharks', 'stadium' => 'Durban', 'city' => 'Durban'],
                    ['team' => 'SWD Eagles', 'stadium' => 'George', 'city' => 'George'],
                    ['team' => 'Western Province', 'stadium' => 'Cape Town', 'city' => 'Cape Town'],
                    ['team' => 'Vereeniging', 'stadium' => 'Vereeniging', 'city' => 'Vereeniging'],
                    ['team' => 'Soshanguve', 'stadium' => 'Soshanguve', 'city' => 'Soshanguve'],
                    ['team' => 'Pietermaritzburg', 'stadium' => 'Pietermaritzburg', 'city' => 'Pietermaritzburg'],
                    ['team' => 'CUT Ixias', 'stadium' => 'CUT', 'city' => 'Bloemfontein'],
                    ['team' => 'Maties', 'stadium' => 'Danie Craven', 'city' => 'Stellenbosch'],
                    ['team' => 'NWU Pukke', 'stadium' => 'Fanie du Toit', 'city' => 'Potchefstroom'],
                    ['team' => 'UCT Ikey Tigers', 'stadium' => 'UCT', 'city' => 'Cape Town'],
                    ['team' => 'UFS Shimlas', 'stadium' => 'Shimla Park', 'city' => 'Bloemfontein'],
                    ['team' => 'Wits', 'stadium' => 'Wits', 'city' => 'Johannesburg'],
                    ['team' => 'UP Tuks', 'stadium' => 'LC de Villiers', 'city' => 'Pretoria'],
                    ['team' => 'TUT Vikings', 'stadium' => 'TUT', 'city' => 'Pretoria'],
                    ['team' => 'Rhodes', 'stadium' => 'Rhodes', 'city' => 'Grahamstown'],
                    ['team' => 'UFH Blues', 'stadium' => 'Davidson', 'city' => 'Alice'],
                    ['team' => 'UKZN Impi', 'stadium' => 'Peter Booysen', 'city' => 'Pietermaritzburg'],
                ],
            ],
        ];

        foreach ($teamArray as $country) {
            $countryId = Country::find()
                ->select(['country_id'])
                ->where(['country_name' => $country['country']])
                ->limit(1)
                ->scalar();

            foreach ($country['list'] as $item) {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    $city = City::find()
                        ->where(['city_name' => $item['city'], 'city_country_id' => $countryId])
                        ->limit(1)
                        ->one();
                    if (!$city) {
                        $city = new City();
                        $city->city_country_id = $countryId;
                        $city->city_name = $item['city'];
                        $city->save();
                    }

                    $stadium = new Stadium();
                    $stadium->stadium_city_id = $city->city_id;
                    $stadium->stadium_name = $item['stadium'];
                    $stadium->save();

                    $team = new Team();
                    $team->team_name = $item['team'];
                    $team->team_stadium_id = $stadium->stadium_id;
                    $team->save();

                    $transaction->commit();
                } catch (Exception $e) {
                    $transaction->rollBack();
                    ErrorHelper::log($e);
                }
            }
        }
    }
}
