<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'frontend.views.team-request.index.footer-base' => 'База',
    'frontend.views.team-request.index.footer-country' => 'Страна',
    'frontend.views.team-request.index.footer-finance' => 'Финансы',
    'frontend.views.team-request.index.footer-request' => 'ЧЗ',
    'frontend.views.team-request.index.footer-stadium' => 'Стадион',
    'frontend.views.team-request.index.footer-team' => 'Команда',
    'frontend.views.team-request.index.footer-title-request' => 'Число заявок',
    'frontend.views.team-request.index.footer-title-vs' => 'Рейтинг силы команды в длительных соревнованиях',
    'frontend.views.team-request.index.footer-vs' => 'Vs',
    'frontend.views.team-request.index.from' => 'из',
    'frontend.views.team-request.index.h1' => 'Получение команды',
    'frontend.views.team-request.index.header-title-request' => 'Число заявок',
    'frontend.views.team-request.index.header-title-vs' => 'Рейтинг силы команды в длительных соревнованиях',
    'frontend.views.team-request.index.label-base' => 'База',
    'frontend.views.team-request.index.label-country' => 'Страна',
    'frontend.views.team-request.index.label-finance' => 'Финансы',
    'frontend.views.team-request.index.label-request' => 'ЧЗ',
    'frontend.views.team-request.index.label-stadium' => 'Стадион',
    'frontend.views.team-request.index.label-team' => 'Команда',
    'frontend.views.team-request.index.label-vs' => 'Vs',
    'frontend.views.team-request.index.label-your-team' => 'Ваши заявки',
    'frontend.views.team-request.index.label-your-vs' => 'Vs',
    'frontend.views.team-request.index.title-delete' => 'Удалить заявку',
    'frontend.views.team-request.index.title-get' => 'Выбрать',
    'frontend.views.team.index.footer-country' => 'Страна',
    'frontend.views.team.index.footer-team' => 'Команды',
    'frontend.views.team.index.h1' => 'Команды',
    'frontend.views.team.index.label-country' => 'Страна',
    'frontend.views.team.index.label-team' => 'Команды',
    'frontend.views.team.team-bottom-forum.header' => 'Последние темы на форуме федерации',
    'frontend.views.team.team-bottom-my-team.header' => 'Показатели вашей команды:',
    'frontend.views.team.team-bottom-my-team.price-base' => 'Стоимость строений',
    'frontend.views.team.team-bottom-my-team.price-total' => 'Общая стоимость',
    'frontend.views.team.team-bottom-my-team.s15' => 'Сила 15 лучших (s15)',
    'frontend.views.team.team-bottom-my-team.s19' => 'Сила 19 лучших (s19)',
    'frontend.views.team.team-bottom-my-team.s24' => 'Сила 24 лучших (s24)',
    'frontend.views.team.team-bottom-my-team.vs' => 'Рейтинг силы команды (Vs)',
    'frontend.views.team.team-links.achievement' => 'Достижения',
    'frontend.views.team.team-links.deal' => 'Сделки',
    'frontend.views.team.team-links.finance' => 'Финансы',
    'frontend.views.team.team-links.game' => 'Матчи',
    'frontend.views.team.team-links.history' => 'События',
    'frontend.views.team.team-links.player' => 'Игроки',
    'frontend.views.team.team-links.statistics' => 'Статистика',
    'frontend.views.team.team-links.trophy' => 'Трофеи',
    'frontend.views.team.team-top-left.base' => 'База',
    'frontend.views.team.team-top-left.division' => 'Дивизион',
    'frontend.views.team.team-top-left.finance' => 'Финансы',
    'frontend.views.team.team-top-left.from' => 'из',
    'frontend.views.team.team-top-left.level' => 'уровень',
    'frontend.views.team.team-top-left.manager' => 'Менеджер',
    'frontend.views.team.team-top-left.nickname' => 'Ник',
    'frontend.views.team.team-top-left.off-season' => 'Кубок межсезонья',
    'frontend.views.team.team-top-left.stadium' => 'Стадион',
    'frontend.views.team.team-top-left.title-base-building' => 'На базе идет строительство',
    'frontend.views.team.team-top-left.title-envelope' => 'Написать',
    'frontend.views.team.team-top-left.title-stadium-building' => 'На стадионе идет строительство',
    'frontend.views.team.team-top-left.title-vice-leave' => 'Отказаться от заместительства',
    'frontend.views.team.team-top-left.vice' => 'Заместитель',
];
