<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'controllers.logo.index.title' => 'Team logos',
    'controllers.logo.view.bread.index' => 'Team logos',
    'controllers.schedule.index.title' => 'Turn the time',
    'models.forms.sing-in.password.error' => 'Wrong login or password',
    'views.analytics.snapshot.date' => 'Date',
    'views.analytics.snapshot.label.id' => 'Value',
    'views.analytics.snapshot.submit' => 'View',
    'views.layout.main.label.complaint' => 'Complaints',
    'views.layout.main.label.generator' => 'Generator correction',
    'views.layout.main.label.log' => 'Logs',
    'views.layout.main.label.logo' => 'Logos',
    'views.layout.main.label.logout' => 'Logout',
    'views.layout.main.label.metrics' => 'Site metrics',
    'views.layout.main.label.news' => 'News',
    'views.layout.main.label.photo' => 'Photos',
    'views.layout.main.label.rule' => 'Rules',
    'views.layout.main.label.schedule' => 'Schedule',
    'views.layout.main.label.snapshot' => 'Snapshots',
    'views.layout.main.label.support' => 'Support',
    'views.layout.main.label.team' => 'Teams',
    'views.layout.main.label.team-request' => 'Team requests',
    'views.layout.main.label.turn-off' => 'Turn off',
    'views.layout.main.label.turn-on' => 'Turn on',
    'views.layout.main.label.user' => 'Users',
    'views.layout.main.label.version' => 'Site version',
    'views.layout.main.label.vote' => 'Votes',
    'views.logo.index.th.date' => 'Application time',
    'views.logo.index.th.team' => 'Team',
    'views.photo.index.th.date' => 'Application time',
    'views.photo.index.th.user' => 'User',
    'views.schedule.index.link.future' => 'Forward to the future',
    'views.schedule.index.link.past' => 'Back to the past',
    'views.schedule.index.today' => 'Today',
    'views.site.index.amount' => 'Amount',
    'views.site.index.check' => 'For checking',
    'views.site.index.link.details' => 'Details',
    'views.site.index.month' => 'Month',
    'views.site.index.payment' => 'Payments',
];
