<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'migrations.finance-text.federation.transfer' => 'Перевод сo счета федерации',
    'migrations.finance-text.income.building-base' => 'Компенсация за уменьшение строения {building} до {level} уровня',
    'migrations.finance-text.income.building-stadium' => 'Компенсация за уменьшения стадиона до {capacity} мест',
    'migrations.finance-text.income.coach' => 'Зарплата тренера сборной',
    'migrations.finance-text.income.deal-check' => 'Вознаграждение за проверку сделки',
    'migrations.finance-text.income.loan' => 'Игрок {player} отдан в аренду',
    'migrations.finance-text.income.national' => 'Компенсиция за участие игроков в матчах сборной',
    'migrations.finance-text.income.pension' => 'Уход на пенсию игрока',
    'migrations.finance-text.income.prize-championship' => 'Призовые за чемпионат страны',
    'migrations.finance-text.income.prize-conference' => 'Призовые за конференцию любительских клубов',
    'migrations.finance-text.income.prize-league' => 'Призовые за Лигу чемпионов',
    'migrations.finance-text.income.prize-off-season' => 'Призовые за кубок межсезонья',
    'migrations.finance-text.income.prize-vip' => 'VIP-призовые',
    'migrations.finance-text.income.prize-world-cup' => 'Призовые за чемпионат мира',
    'migrations.finance-text.income.referral' => 'Бонус по партнёрской программе',
    'migrations.finance-text.income.scout-style' => 'Возврат за отмену изучения стиля игрока {player}',
    'migrations.finance-text.income.ticket' => 'Доход от продажи билетов',
    'migrations.finance-text.income.training-position' => 'Возврат за отмену тренировки совмещения игрока {player}',
    'migrations.finance-text.income.training-power' => 'Возврат за отмену тренировки балла силы игрока {player}',
    'migrations.finance-text.income.training-special' => 'Возврат за отмену тренировки спецвозможности игрока {player}',
    'migrations.finance-text.income.transfer' => 'Продажа игрока {player}',
    'migrations.finance-text.income.transfer-first-team' => 'Первой команде за трансфер игрока {player}',
    'migrations.finance-text.outcome.building-base' => 'Оплата увеличения уровня строения {building} до {level} уровня',
    'migrations.finance-text.outcome.building-stadium' => 'Оплата расширения стадиона до {capacity} мест',
    'migrations.finance-text.outcome.game' => 'Расходы на организацию матча',
    'migrations.finance-text.outcome.loan' => 'Игрок {player} взят в аренду',
    'migrations.finance-text.outcome.maintenance' => 'Содержание базы за сезон',
    'migrations.finance-text.outcome.national' => 'Распределение денег сборной между тренерами и менеджерами клубов',
    'migrations.finance-text.outcome.salary' => 'Зарплата игроков',
    'migrations.finance-text.outcome.scout-style' => 'Оплата изучения стиля игрока {player}',
    'migrations.finance-text.outcome.training-position' => 'Оплата тренировки совмещения игрока {player}',
    'migrations.finance-text.outcome.training-power' => 'Оплата тренировки балла силы игрока {player}',
    'migrations.finance-text.outcome.training-special' => 'Оплата тренировки спецвозможности игрока {player}',
    'migrations.finance-text.outcome.transfer' => 'Покупка игрока {player}',
    'migrations.finance-text.team.re-register' => 'Перерегистрация команды',
    'migrations.finance-text.user.transfer' => 'Перевод с личного счета менеджера',
    'migrations.history-text.building.down' => 'Уровень строения {building} уменьшен до {level} уровня',
    'migrations.history-text.building.up' => 'Уровень строения {building} увеличен до {level} уровня',
    'migrations.history-text.change-special' => 'Произведен обмен спецвозможностей в команде',
    'migrations.history-text.change-style' => 'Произведен обмен любимых стилей игроков',
    'migrations.history-text.player.bonus-point' => '{player} натренировал бонусный балл силы на базе',
    'migrations.history-text.player.bonus-position' => '{player} натренировал бонусное совмещение {position} на базе',
    'migrations.history-text.player.bonus-special' => '{player} натренировал бонусную спецвозможность {special} на базе',
    'migrations.history-text.player.championship-special' => '{player} получил спецвозможность {special} по результатам чемпионата',
    'migrations.history-text.player.exchange' => '{player} перешел из команды {team} в команду {team2} в результате обмена',
    'migrations.history-text.player.free' => '{player} продан Лиге командой {team}',
    'migrations.history-text.player.from-school' => '{player} пришел из спортшколы в команду {team}',
    'migrations.history-text.player.game-point-minus' => '{player} потерял балл силы по результатам матча {game}',
    'migrations.history-text.player.game-point-plus' => '{player} получил балл силы по результатам матча {game}',
    'migrations.history-text.player.injury' => '{player} получил травму на {day} в матче {game}',
    'migrations.history-text.player.loan' => '{player} перешел из команды {team} в команду {team2} на правах аренды',
    'migrations.history-text.player.loan-back' => '{player} вернулся в команду {team} из команды {team2} по окончании аренды',
    'migrations.history-text.player.pension-go' => '{player} вышел на пенсию',
    'migrations.history-text.player.pension-say' => '{player} объявил об уходе на пенсию',
    'migrations.history-text.player.training-point' => '{player} натренировал балл силы на базе',
    'migrations.history-text.player.training-position' => '{player} натренировал совмещение {position} на базе',
    'migrations.history-text.player.training-special' => '{player} натренировал спецвозможность {special} на базе',
    'migrations.history-text.player.transfer' => '{player} перешел из команды {team} в команду {team2}',
    'migrations.history-text.stadium.down' => 'Стадион уменьшен до {capacity} мест',
    'migrations.history-text.stadium.up' => 'Стадион расширен до {capacity} мест',
    'migrations.history-text.team.re-register' => 'Команда {team} перерегистрирована',
    'migrations.history-text.team.register' => 'Команда {team} зарегистрирована в Лиге',
    'migrations.history-text.user.manager-national-in' => '{user} принят на работу тренером-менеджером в сборную {national}',
    'migrations.history-text.user.manager-national-out' => '{user} покинул пост тренера-менеджера сборной {national}',
    'migrations.history-text.user.manager-team-in' => '{user} принят на работу тренером-менеджером в команду {team}',
    'migrations.history-text.user.manager-team-out' => '{user} покинул пост тренера-менеджера команды {team}',
    'migrations.history-text.user.president-in' => '{user} избран президентом федерации {federation}',
    'migrations.history-text.user.president-out' => '{user} покинул пост президента федерации {federation}',
    'migrations.history-text.user.vice-national-in' => '{user} принят на работу заместителем менеджера в сборную {national}',
    'migrations.history-text.user.vice-national-out' => '{user} покинул пост заместителя менеджера сборной {national}',
    'migrations.history-text.user.vice-president-in' => '{user} избран заместителем президента федерации {federation}',
    'migrations.history-text.user.vice-president-out' => '{user} покинул пост заместителя президента федерации {federation}',
    'migrations.history-text.user.vice-team-in' => '{user} принят на работу заместителем менеджера в команду {team}',
    'migrations.history-text.user.vice-team-out' => '{user} покинул пост заместителя менеджера команды {team}',
    'migrations.history-text.vip.1-place' => 'За 1 место в регулярном чемпионате страны VIP-клуб сроком 3 мес.',
    'migrations.history-text.vip.2-place' => 'За 2 место в регулярном чемпионате страны VIP-клуб сроком 2 мес.',
    'migrations.history-text.vip.3-place' => 'За 3 место в регулярном чемпионате страны VIP-клуб сроком 1 мес.',
];
