<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'migrations.finance-text.federation.transfer' => 'Перевод сo счета федерации',
    'migrations.finance-text.income.building-base' => 'Компенсация за уменьшение строения {building} до {level} уровня',
    'migrations.finance-text.income.building-stadium' => 'Компенсация за уменьшения стадиона до {capacity} мест',
    'migrations.finance-text.income.coach' => 'Зарплата тренера сборной',
    'migrations.finance-text.income.deal-check' => 'Вознаграждение за проверку сделки',
    'migrations.finance-text.income.loan' => 'Игрок {player} отдан в аренду',
    'migrations.finance-text.income.national' => 'Компенсиция за участие игроков в матчах сборной',
    'migrations.finance-text.income.pension' => 'Уход на пенсию игрока',
    'migrations.finance-text.income.prize-championship' => 'Призовые за чемпионат страны',
    'migrations.finance-text.income.prize-conference' => 'Призовые за конференцию любительских клубов',
    'migrations.finance-text.income.prize-league' => 'Призовые за Лигу чемпионов',
    'migrations.finance-text.income.prize-off-season' => 'Призовые за кубок межсезонья',
    'migrations.finance-text.income.prize-vip' => 'VIP-призовые',
    'migrations.finance-text.income.prize-world-cup' => 'Призовые за чемпионат мира',
    'migrations.finance-text.income.referral' => 'Бонус по партнёрской программе',
    'migrations.finance-text.income.scout-style' => 'Возврат за отмену изучения стиля игрока {player}',
    'migrations.finance-text.income.ticket' => 'Доход от продажи билетов',
    'migrations.finance-text.income.training-position' => 'Возврат за отмену тренировки совмещения игрока {player}',
    'migrations.finance-text.income.training-power' => 'Возврат за отмену тренировки балла силы игрока {player}',
    'migrations.finance-text.income.training-special' => 'Возврат за отмену тренировки спецвозможности игрока {player}',
    'migrations.finance-text.income.transfer' => 'Продажа игрока {player}',
    'migrations.finance-text.income.transfer-first-team' => 'Первой команде за трансфер игрока {player}',
    'migrations.finance-text.outcome.building-base' => 'Оплата увеличения уровня строения {building} до {level} уровня',
    'migrations.finance-text.outcome.building-stadium' => 'Оплата расширения стадиона до {capacity} мест',
    'migrations.finance-text.outcome.game' => 'Расходы на организацию матча',
    'migrations.finance-text.outcome.loan' => 'Игрок {player} взят в аренду',
    'migrations.finance-text.outcome.maintenance' => 'Содержание базы за сезон',
    'migrations.finance-text.outcome.national' => 'Распределение денег сборной между тренерами и менеджерами клубов',
    'migrations.finance-text.outcome.salary' => 'Зарплата игроков',
    'migrations.finance-text.outcome.scout-style' => 'Оплата изучения стиля игрока {player}',
    'migrations.finance-text.outcome.training-position' => 'Оплата тренировки совмещения игрока {player}',
    'migrations.finance-text.outcome.training-power' => 'Оплата тренировки балла силы игрока {player}',
    'migrations.finance-text.outcome.training-special' => 'Оплата тренировки спецвозможности игрока {player}',
    'migrations.finance-text.outcome.transfer' => 'Покупка игрока {player}',
    'migrations.finance-text.team.re-register' => 'Перерегистрация команды',
    'migrations.finance-text.user.transfer' => 'Перевод с личного счета менеджера',
];
