<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#2">2. Участники турнира.</a>
<br/>
<a href="#3">3. Регламент турнира.</a>
<br/>
<a href="#4">4. Усталость игроков.</a>
<br/>
<a href="#5">5. Призовые.</a>
</p>
<p class="text-justify" id="1"><span class="strong">1. Общие положения.</span> Лига чемпионов - самый престижный клубный турнир Лиги, куда попадают лучшие команды предыдущего сезона. Первый розыгрыш лиги чемпионов будет проводиться во втором сезоне.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="2"><span class="strong">2. Участники турнира.</span> Участники лиги чемпионов и начальная стадия для каждого из них определяются согласно рейтингу стран в лиге чемпионов.</p>
<p class="text-justify">Чем выше федерация в рейтинге, тем больше мест в лиге чемпионов она получает, и тем с более поздних этапов стартуют её представители.</p>
<p class="text-justify">Точное количество участников и начальная стадия для каждого из них можно узнать на страницах национальных федераций.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3"><span class="strong">3. Регламент турнира.</span> Жеребьевка турнира проводится вначале сезона и после каждого сыгранного раунда. Жеребьевка раундов проводится на основе деления участников каждого раунда на две или несколько корзин согласно показателю Vs.</p> 
<p class="text-justify">Турнир состоит из следующих этапов:</p>
<p class="text-justify">1) Первый отборочный раунд - двухраундовое противостояние (команды играют по два матча: дома и в гостях). Победители выходят во второй отборочный раунд.</p>
<p class="text-justify">2) Второй отборочный раунд - двухраундовое противостояние, в котором принимают участие победители первого отборочного раунда и команды, стартующие со второго отборочного раунда. Победители выходят в третий отборочный раунд.</p>
<p class="text-justify">3) Третий отборочный раунд - двухраундовое противостояние, в котором принимают участие победители второго отборочного раунда и команды, стартующие с третьего отборочного раунда. Победители выходят в раунд стыковых матчей.</p>
<p class="text-justify">4) Групповой турнир - 8 групп по 4 команды, каждая команда играет с каждой в группе два матча: дома и в гостях. Участвуют победители третьего отборочного раунда и команды, стартующие с группового турнира. Из каждой группы в 1/8 финала выходит по две лучших команды.</p>
<p class="text-justify">5) 1/8 финала - двухраундовое противостояние, в котором принимают участие команды, занявшие первые и вторые места в своих группах на групповом турнире. Жеребьевка проходит по схеме:</p>
<ul>
<li>A1 - B2</li>
<li>C1 - D2</li>
<li>E1 - F2</li>
<li>G1 - H2</li>
<li>B1 - C2</li>
<li>D1 - E2</li>
<li>F1 - G2</li>
<li>H1 - A2</li>
</ul>
<p class="text-justify">Победители выходят в 1/4 финала и сводятся попарно в той же очерёдности.</p>
<p class="text-justify">6) 1/4 финала - двухраундовое противостояние, в котором принимают участие победители 1/8 финала. Победители выходят в 1/2 финала и сводятся попарно в той же очерёдности.</p>
<p class="text-justify">7) 1/2 финала - двухраундовое противостояние, в котором принимают участие победители 1/4 финала. Победители выходят в финал турнира.</p>
<p class="text-justify">8) Финал - двухраундовое противостояние, в котором принимают участие победители 1/2 финала.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="4"><span class="strong">4. Усталость игроков.</span> Матчи этого турнира являются дополнительными (тип C), поэтому играющие регбисты слегка устают, а усталость не участвовавших в матче не восстанавливается</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="5"><span class="strong">5. Призовые.</span> Призовые лиги чемпионов можно узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Занятое место</th><th>Призовые</th></tr>
<tr><td>Победитель</td><td class="text-right">25 000 000$</td></tr>
<tr><td>Финалист</td><td class="text-right">23 000 000$</td></tr>
<tr><td>Проигравшие в 1/2 финала</td><td class="text-right">21 000 000$</td></tr>
<tr><td>Проигравшие в 1/4 финала</td><td class="text-right">19 000 000$</td></tr>
<tr><td>Проигравшие в 1/8 финала</td><td class="text-right">17 000 000$</td></tr>
<tr><td>3 место в группе</td><td class="text-right">15 000 000$</td></tr>
<tr><td>4 место в группе</td><td class="text-right">13 000 000$</td></tr>
<tr><td>Проигравшие в третьем отборочном раунде</td><td class="text-right">9 000 000$</td></tr>
<tr><td>Проигравшие во втором отборочном раунде</td><td class="text-right">7 000 000$</td></tr>
<tr><td>Проигравшие в первом отборочном раунде</td><td class="text-right">5 000 000$</td></tr>
</table>
<p class="text-justify">Призовые выплачиваются в том числе и тем клубам, которые начнут играть с определенной стадии и на этом же этапе и закончат выступление.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Лига чемпионов',
];
