<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#2">2. Сбор средств в фонд федерации.</a>
<br/>
<a href="#3">3. Распределение средств фонда федерации.</a>
</p>
<p class="text-justify" id="1"><span class="strong">1. Общие положения.</span> У каждой виртуальной федерации есть фонд. Фонд федерации - это денежные средства федерации, собранные и распределяемые на её нужды.</p>
<p class="text-justify">Управление фондом осуществляет президент федерации с согласия большинства менеджеров этой страны путем голосования.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="2"><span class="strong">2. Сбор средств в фонд федерации.</span> Каждый менеджер может самостоятельно сделать взнос в фонд любой федерации со своего личного счета.</p>
<p class="text-justify">Для этого необходимо на странице профиля менеджера перейти на вкладку "Личный счет", где надо выбрать федерацию, в которую будет осуществлен перевод. После этого останется указать сумму взноса.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3"><span class="strong">3. Распределение средств фонда федерации.</span> По мере необходимости президент федерации может инициировать голосование по распределению накопленных средств из фонда на счет команд этой федерации. Для этого ему необходимо указать:</p>
<ul>
<li>объяснения для менеджеров - почему производится выплата средств фонда;</li>
<li>список команд федерации и суммы, которые они получают. При этом сумма выплат командам не может превышать сумму, находящуюся в распоряжении фонда.</li>
</ul>
<p class="text-justify">После того, как президент завершил заполнение формы, настает очередь менеджеров высказывать свое мнение. У каждого менеджера при голосовании есть один из трех вариантов:</p>
<ul>
<li>Согласен с таким распределением средств фонда федерации.</li>
<li>Против такого распределения средств фонда федерации.</li>
</ul>
<p class="text-justify">Голосование длится 48 часов с момента создания. Распределение средств происходит только в том случае, если по истечение этого времени более 50% проголосовавших менеджеров согласны с таким распределением. Пополнение денежными средствами на счет указанных в голосовании команд федерации происходит автоматически.</p>
<p class="text-justify">В разделе "Опросы" можно следить за ходом открытых или узнать результаты закрытых голосований.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Фонды федераций',
];
