<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Allocation of seats in the conference. </a>
<br/>
<a href="#3"> 3. Prize money. </a>
<br/>
<a href="#4"> 4. Rotation. </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. General provisions. </span> Absolutely all new teams that were created after determining the composition of the participants in the next championship of their country and, accordingly, do not participate in it, participate in the drawing of the conference of amateur clubs. Also among the participants of the tournament are those from the previously registered teams that have been eliminated or have not yet entered the grid of the divisions of the championship of their country. </p>
<p class = "text-justify"> You cannot refuse to participate in the tournament. Registration for the cup takes place automatically immediately after the creation of a team in the League, it takes part in the next draw of the next round. </p>
<p class = "text-justify"> The tournament is played on an unstable calendar, when a random opponent is selected for each team, moreover, the same team can only be played twice per tournament, and the number of home and away games at the end of the tournament should be equal or differ by one (if your team played an odd number of matches) </p>
<p class = "text-justify"> There is a home bonus in tournament matches - teams play stronger at home. </p>
<p class = "text-justify"> Games of the amateur club conference are type B ("must") games, that is, they change the fatigue of the players, non-players rest. This only applies to teams that participate in the conference of amateur clubs, the players participating in the championships get tired and rest there. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. The distribution of seats in the conference. </span> The following parameters are taken into account in the final distribution of seats in order of priority: </p>
<ul>
<li> accumulated tournament points (the more, the higher); </li>
<li> wins (the more, the higher); </li>
<li> draws (the more, the higher); </li>
<li> the difference in game points (the more, the higher); </li>
<li> of the accumulated game points (the more, the higher); </li>
<li> by Vs rating (the lower the higher); </li>
</ul>
<p class = "text-justify"> If all of the above indicators are equal, a lot is drawn. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. Prize money. </span> The amount of prize money earned by a team for participating in the Amateur Clubs Conference is calculated as follows: </p>
<p class = "text-justify"> 5000000 * 0.98 ^ (place in the standings - 1) </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4"> <span class = "strong"> 4. Rotation. </span> The teams that took the highest places in the national standings according to the results of the conference, in the next season, will be entitled to play in the championship of their country instead of the last and penultimate places in the lower division (or divisions). </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Conference of Amateur Clubs',
];
