<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие сведения о стадионах.</a>
<br/>
<a href="#2">2. Вместимость стадиона.</a>
<br/>
<a href="#3">3. Содержание стадиона.</a>
<br/>
<a href="#4">4. Деньги за билеты.</a>
<br/>
<a href="#5">5. Кто получает деньги за билеты и оплачивает содержание стадиона?</a>
<br/>
<a href="#6">6. Рейтинг стадионов.</a>
<br/>
<a href="#7">7. Выбор наибольших стадионов.</a>
<br/>
<a href="#8">8. Краткосрочный рейтинг посещаемости.</a>
<br/>
<a href="#9">9. Зрительский интерес к матчу.</a>
</p>
<p class="text-justify" id="1"><span class="strong">1. Общие сведения о стадионах.</span> У каждой команды есть собственная арена (стадион), на котороё проводятся домашние матчи. Стадионы являются источником дохода от продажи зрительских билетов. Количество зрителей зависит от цены билета, вместимости стадиона, интересности матча.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="2"><span class="strong">2. Вместимость стадиона.</span> У новых команд стадион имеет вместимость 100 мест. Впоследствии его вместимость может быть расширена за счет постройки новых трибун и расширения уже имеющихся вплоть до 25 тыс., если, конечно, на это у команды есть деньги. Стоимость такого улучшения определяется по формуле:</p>
<p class="text-justify">(НВ ^ 1.1 - ТВ ^ 1.1) * 200, где</p>
<ul>
<li>НВ - новая вместимоть арены;</li>
<li>ТВ - текущая вместимоть арены;</li>
</ul>
<p class="text-justify">Прежде чем расширять стадион, оцените возможности своей команды - как скоро вложенные в строительство и содержание деньги вернутся обратно в виде зрительского интереса к матчам вашей команды.</p>
<p class="text-justify">Время строительства стадиона - 1 день за каждые полные (или не полные) тысячу построенных мест.</p>
<p class="text-justify">Время разрушения стадиона - 1 день.</p>
<p class="text-justify">Нельзя изменять вместимость стадиона в первые 7 дней после получения команды.</p>
<p class="text-justify">Нельзя уменьшать вместимость стадиона, если за последние 7 дней команда более 25% матчей играла автосоставами.</p>
<p class="text-justify">Любое строительство стадиона (увеличение или уменьшение вместимости) обязательно заканчивается в конце сезона.</p>
<p class="text-justify">В течение времени строительства вы не можете повлиять на размер стадиона.</p>
<p class="text-justify">Стоимость постройки новых трибун вы должны оплатить сразу же во время начала строительства. Компенсацию за уменьшение размера стадиона вы также получите сразу.</p>
<p class="text-justify">В любой момент времени у вас есть возможность отменить запланированную постройку (или разрушение) стадиона, вернув на свой счёт всю оплаченную сумму (если вы запланировали постройку). Но если отмена строительства произошла, то весь прогресс будет потерян.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3"><span class="strong">3. Содержание стадиона.</span> Содержание стадиона расчитывается по формуле:</p>
<p class="text-justify">ТВ ^ 1.3, где</p>
<ul>
<li>ТВ - текущая вместимоть арены.</li>
</ul>
<p class="text-justify">Стоимость содержания оплачивается после каждого проведенного на стадионе матча.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="4"><span class="strong">4. Деньги за билеты.</span> Стадион - источник дохода команды. На каждый матч продаются билеты и приходят зрители. Кол-во пришедших зрителей зависит от установленной цены на билеты, интересности матча и рейтинга посещаемости команд.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="5"><span class="strong">5. Кто получает деньги за билеты и оплачивает содержание стадиона?</span> Получение денег за билеты (и оплата содержания стадиона) зависит от типа соревнования:</p>
<ul>
<li>если хозяин матча явно определен (чемпионат, кубок межсезонья, конференция любительских клубов), то все деньги за билеты получает организатор (владелец стадиона), он же должен оплатить содержание стадиона;</li>
<li>если стадион проведения матча определяется среди участников матча в момент добавления матчей и домашнего бонуса нет (товарищеские игры), то деньги, как и обязанность оплатить содержание стадиона, делятся поровну;</li>
<li>если стадион выбирается среди наибольших (финалы различных кубков), то деньги за билеты делятся на три равные части между владельцем стадиона и финалистами, а содержание стадиона оплачивает лига;</li>
<li>в матчах сборных деньги за билеты делятся на три равные части между игравшими сборными и командой-владельцем стадиона. Содержание стадионов в матчах сборных оплачивает Лига.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="6"><span class="strong">6. Рейтинг стадионов.</span> Наибольшим стадионом в рейтингах является более новый (по времени строительства) из самых больших по вместимости стадионов.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="7"><span class="strong">7. Выбор наибольших стадионов.</span> При выборе наибольших стадионов страны действует следующее правило - стадионы определяются непосредственно в день игры согласно актуальному в этот момент рейтингу стадионов страны.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="8"><span class="strong">8. Краткосрочный рейтинг посещаемости.</span> Некоторой части зрителей нравится ходить на матчи только тогда, когда команда выигрывает, и не нравится ходить на матчи, когда команда проигрывает.</p>
<p class="text-justify">Краткосрочный рейтинг посещаемости зависит от результатов последних пяти любых матчей команды в текущем сезоне: чем лучше и интереснее выступает команда в сезоне, тем выше этот рейтинг, а вместе с ним и посещаемость матчей.</p>
<p class="text-justify">В начале каждого сезона краткосрочный рейтинг посещаемости равен 1,00.</p>
<p class="text-justify">За каждый матч из списка пяти последних сыгранных в этом сезоне матчей команда набирает определённое число баллов в зависимости от итогового счёта этого матча:</p>
<table class="table table-bordered table-hover">
<tr><th>Заброшено шайб</th><th>Рейтинг</th><th>Пропущено шайб</th><th>Рейтинг</th></tr>
<tr><td class="text-center">9 и больше</td><td class="text-center">+0.95</td><td class="text-center">9 и больше</td><td class="text-center">0</td></tr>
<tr><td class="text-center">8</td><td class="text-center">+0.90</td><td class="text-center">8</td><td class="text-center">+0.05</td></tr>
<tr><td class="text-center">7</td><td class="text-center">+0.85</td><td class="text-center">7</td><td class="text-center">+0.10</td></tr>
<tr><td class="text-center">6</td><td class="text-center">+0.80</td><td class="text-center">6</td><td class="text-center">+0.15</td></tr>
<tr><td class="text-center">5</td><td class="text-center">+0.75</td><td class="text-center">5</td><td class="text-center">+0.20</td></tr>
<tr><td class="text-center">4</td><td class="text-center">+0.70</td><td class="text-center">4</td><td class="text-center">+0.25</td></tr>
<tr><td class="text-center">3</td><td class="text-center">+0.65</td><td class="text-center">3</td><td class="text-center">+0.30</td></tr>
<tr><td class="text-center">2</td><td class="text-center">+0.60</td><td class="text-center">2</td><td class="text-center">+0.35</td></tr>
<tr><td class="text-center">1</td><td class="text-center">+0.55</td><td class="text-center">1</td><td class="text-center">+0.40</td></tr>
<tr><td class="text-center">0</td><td class="text-center">+0.50</td><td class="text-center">0</td><td class="text-center">+0.45</td></tr>
</table>
<p class="text-justify">В случае назначения команде технического поражения - она набирает за этот матч 0 баллов.</p>
<p class="text-justify">Сумма набранных баллов делится на число матчей, участвовавших в подсчёте (на пять или в начале сезона на меньшее число), полученный результат и есть краткосрочный рейтинг посещаемости.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="9"><span class="strong">9. Зрительский интерес к матчу.</span> При определении зрительского интереса к матчу учитывается краткосрочный рейтинг посещаемости обоих участников матча и поправочный коэффициент к питу турнира и страдии турнира.</p>
<p class="text-justify">Поправочный коэффициент к типу турнира можно узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Турнир</th><th>Коэффициент</th></tr>
<tr><td class="text-center">Матчи сборных</td><td class="text-center">2</td></tr>
<tr><td class="text-center">Лига чемпионов</td><td class="text-center">1.5</td></tr>
<tr><td class="text-center">Чемпионаты стран</td><td class="text-center">1</td></tr>
<tr><td class="text-center">Конференция любительских клубов</td><td class="text-center">0.9</td></tr>
<tr><td class="text-center">Кубок межсезонья</td><td class="text-center">0.9</td></tr>
<tr><td class="text-center">Товарищеский матч</td><td class="text-center">0.8</td></tr>
</table>
<p class="text-justify">Поправочный коэффициент к страдии турнира можно узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Стадия</th><th>Коэффициент</th></tr>
<tr><td class="text-center">Нет стадии (для товарищеских матчей)</td><td class="text-center">0.9</td></tr>
<tr><td class="text-center">1-41 тур</td><td class="text-center">1</td></tr>
<tr><td class="text-center">Отборочный раунд</td><td class="text-center">1.05</td></tr>
<tr><td class="text-center">1/512 финала</td><td class="text-center">1.1</td></tr>
<tr><td class="text-center">1/256 финала</td><td class="text-center">1.2</td></tr>
<tr><td class="text-center">1/128 финала</td><td class="text-center">1.3</td></tr>
<tr><td class="text-center">1/64 финала</td><td class="text-center">1.4</td></tr>
<tr><td class="text-center">1/32 финала</td><td class="text-center">1.5</td></tr>
<tr><td class="text-center">1/16 финала</td><td class="text-center">1.6</td></tr>
<tr><td class="text-center">1/8 финала</td><td class="text-center">1.7</td></tr>
<tr><td class="text-center">1/4 финала</td><td class="text-center">1.8</td></tr>
<tr><td class="text-center">1/2 финала</td><td class="text-center">1.9</td></tr>
<tr><td class="text-center">Финал</td><td class="text-center">2</td></tr>
</table>
<p class="text-justify">Зрительский интерес к матчу рассчитывается по одной из двух формул:</p>
<p class="text-justify">( РД + РГ ) * K1 * K2 / 2 - для всех матчей без домашнего бонуса.</p>
<p class="text-justify">( 2 * РД + РГ ) * K1 * K2 / 3 - для всех матчей с домашним бонусом.</p>
<p class="text-justify">Где</p>
<ul>
<li>РД - ретинг домашней команды;</li>
<li>РГ - ретинг гостевой команды;</li>
<li>K1 - поправочный коэффициент к типу турнира;</li>
<li>K2 - поправочный коэффициент к страдии турнира.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Стадионы команд и посещаемость матчей',
];
