<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#1.1">1.1. Что такое позиции игроков.</a>
<br/>
<a href="#1.2">1.2. Совмещение позиций.</a>
<br/>
<a href="#2">2. Профильные позиции игроков.</a>
<br/>
<a href="#2.1">2.1. GK - Голкипер.</a>
<br/>
<a href="#2.2">2.2. LD - Левый защитник.</a>
<br/>
<a href="#2.3">2.3. RD - Правый защитник.</a>
<br/>
<a href="#2.4">2.4. LF - Левый нападающий.</a>
<br/>
<a href="#2.5">2.5. C - Центральный нападающий.</a>
<br/>
<a href="#2.6">2.6. RF - Правый нападающий.</a>
</p>
<p class="strong text-justify" id="1">1. Общие положения.</p>
<p class="text-justify" id="1.1"><span class="strong">1.1. Что такое позиции игроков.</span> Каждый игрок в Лиге имеет одну или две профильные (любимые) позиции:</p>
<ul>
<li>на своих профильных позициях регбист играет в свою силу;</li>
<li>на непрофильных позициях регбист играет слабее.</li>
</ul>
<p class="text-justify">Профильные позиции могут быть натренированы игрокам в тренировочном центре команды или бонусными тренировками.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="1.2"><span class="strong">1. 2. Совмещение позиций.</span> Наличие у игрока двух профильных позиций называется совмещением позиций.</p>
<p class="text-justify">Если у игрока есть две профильные позиции, то он может без потери силы играть на любой из этих позиций.</p>
<p class="text-justify">Вторая позиция может быть только у полевых игроков (голкиперы играют строго на позиции голкиперов).</p>
<p class="text-justify">Максимальное количество позиций одного игрока равно двум.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2">2. Профильные позиции игроков.</p>
<p class="text-justify" id="2.1"><span class="strong">2.1. GK - Голкипер.</span> Не играет на другой позиции и не может иметь совмещения позиций.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2.2"><span class="strong">2.2. LD - Левый защитник</p>
<p class="text-justify">На позиции левого защитника могут играть:</p>
<ul>
<li>LD (левый защитник) с силой 100% от реальной;</li>
<li>LF (левый нападающий), RD (правый защитник) с силой 90% от реальной;</li>
<li>Игроки других позиций с силой 80% от реальной.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2.3">2.3. RD - Правый защитник</p>
<p class="text-justify">На позиции правого защитника могут играть:</p>
<ul>
<li>RD (правый защитник) с силой 100% от реальной;</li>
<li>RF (правый нападающий), LD (левый защитник) с силой 90% от реальной;</li>
<li>Игроки других позиций с силой 80% от реальной.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2.4">2.4. LF - Левый нападающий.</p>
<p class="text-justify">На позиции левого нападающего могут играть:</p>
<ul>
<li>LF (левый нападающий) с силой 100% от реальной;</li>
<li>С (центральный нападающий), LD (левый защитник) с силой 90% от реальной;</li>
<li>Игроки других позиций с силой 80% от реальной.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2.5">2.5. C - Центральный нападающий.</p>
<p class="text-justify">На позиции центрального нападающего могут играть:</p>
<ul>
<li>С (центральный нападающий) с силой 100% от реальной;</li>
<li>LF (левый нападающий), RF (правый нападающий) с силой 90% от реальной;</li>
<li>Игроки других позиций с силой 80% от реальной.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2.6">2.6. RF - Правый нападающий.</p>
<p class="text-justify">На позиции правого нападающего могут играть:</p>
<ul>
<li>RF (правый нападающий) с силой 100% от реальной;</li>
<li>С (центральный нападающий), RD (правый защитник) с силой 90% от реальной;</li>
<li>Игроки других позиций с силой 80% от реальной.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Позиции игроков',
];
