<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. League tournaments. </a>
<br/>
<a href="#1.1"> 1.1. What are the official tournaments. </a>
<br/>
<a href="#1.2"> 1.2. League season structure. </a>
<br/>
<a href="#2"> 2. Game day parameters. </a>
<br/>
<a href="#2.1"> 2.1. Types of matches. </a>
<br/>
<a href="#2.2"> 2.2. Change player fatigue. </a>
<br/>
<a href="#2.3"> 2.3. Seating allocation in group format tournaments. </a>
<br/>
<a href="#2.4"> 2.4. Seating allocation in cup-format tournaments. </a>
<br/>
<a href="#2.5"> 2.5. Force majeure. </a>
<br/>
<a href="#3"> 3. Friendly matches (type A). </a>
<br/>
<a href="#4"> 4. National Championships (type B). </a>
<br/>
<a href="#5"> 5. Champions League (type C). </a>
<br/>
<a href="#6"> 6. Offseason Cup (type B). </a>
<br/>
<a href="#7"> 7. Amateur club conference (type B). </a>
<br/>
<a href="#8"> 8. World Championship (type C). </a>
</p>
<p class = "strong text-justify" id = "1"> 1. League tournaments. </p>
<p class = "text-justify" id = "1.1"> <span class = "strong"> 1.1. Which official tournaments are held. </span> The League hosts national championships, friendlies, the Champions League and the world championship. During the off-season, the off-season cup is held. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "1.2"> <span class = "strong"> 1.2. League season structure. </span> The League season consists of many playing days. On any game day, a team can play no more than one match. This also applies to the days of friendly matches. The structure of the current playing season can be viewed on the "Tournaments" page, the schedule of matches on the "Schedule" page. It should be noted that the Administration may make changes and additions to the schedule, which will be additionally announced in the official mailing list and in the news. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "2"> 2. Game day parameters. </p>
<p class = "text-justify" id = "2.1"> <span class = "strong"> 2.1. Types of matches. </span> In the section of the schedule for each game day, its description is set, indicating the type of matches played on that day. There are four basic types of matches: friendlies, championship games, Champions League and World Championship. Read more about the features of each type below. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.2"> <span class = "strong"> 2.2. Changes in player fatigue. </span> Each type of match corresponds to one of the types A, B or C of falling / increasing player fatigue (see also the section "Player fatigue (A)"). </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.3"> <span class = "strong"> 2.3. Seating allocation in group format tournaments. </span> The following rules apply for the Championships, Midseason Cup, Champions League group stage and any other League group stage:
<ul>
<li> accumulated tournament points (the more, the higher); </li>
<li> wins (the more, the higher); </li>
<li> draws (the more, the higher); </li>
<li> the difference in game points (the more, the higher); </li>
<li> of the accumulated game points (the more, the higher); </li>
<li> by Vs rating (the lower the higher); </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.4"> <span class = "strong"> 2.4. Seat allocation in cup format tournaments. </span> For cups held on a two-round system, matches may end in a draw. In the event of an equal score on the aggregate of two matches, an additional and, if necessary, a shootout will be awarded. </p>
<p class = "text-justify"> For the national championship playoff round, each match is played until a winner is identified. If regular time ends in a draw, extra time is assigned. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.5"> <span class = "strong"> 2.5. Force majeure. </span> If during the playing day any violations of the rules were committed by the manager in one way or another, his team is subject to a fine in the amount determined by the Administration depending on the severity of the violation. All results of matches played in the League are final, regardless of possible errors and irregularities in the operation of the generator, managers or the system as a whole and are subject to replay only in exceptional situations by a special decision of the Administration. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "3"> 3. Friendly matches (type A). </p>
<p class = "text-justify"> A friendly match is a practice match between the two teams, organized by the managers of the two participating teams, to practice, test tactics, or simply to find out which team is stronger. </p>
<p class = "text-justify"> Friendlies may or may not be played. You choose your opponent yourself, send him an invitation to a specific game day and wait for a response. If the answer is yes, a friendly match will be organized. </p>
<p class = "text-justify"> You can read more about friendly matches in the separate section of the rules - Friendly matches. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "4"> 4. National Championships (type B). </p>
<p class = "text-justify"> The Country Championships are the main tournament for every team in the League. All teams participate in the championships of their countries, the championship is held once a season. </p>
<p class = "text-justify"> A national championship can have multiple divisions. Each division is, in fact, a separate tournament, with the only difference that there is a rotation of teams between the divisions of the same country. </p>
<p class = "text-justify"> All championships are played in a two-round system, with each team playing two matches against everyone else - home and away (30 matches in total). </p>
<p class = "text-justify"> The winners of the first division of the championship (D1), in addition to medals, are entitled to represent their country in the Champions League. </p>
<p class = "text-justify"> Read more about the tournament in a separate section - National Championships. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "5"> 5. Champions League (type C). </p>
<p class = "text-justify"> This is a tournament for the best teams in each country. The regulations for the Champions League are determined for each season separately and can change quite a lot as the number of teams in the League is constantly growing. The season-specific Champions League regulations can be found in a separate section of the rules. </p>
<p class = "text-justify"> All Champions League matches are optional (type C). </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "6"> 6. Offseason Cup (type B). </p>
<p class = "text-justify"> The Offseason Cup is a tournament that takes place at the very beginning of each season. All League teams take part in the off-season cup. </p>
<p class = "text-justify"> The tournament is played on an unstable calendar, when a random opponent is selected for each team, moreover, the same team can be played only once per tournament, and the number of home and away games at the end of the tournament must become equal or differ by one (if your team played an odd number of matches). </p>
<p class = "text-justify"> There is a home bonus in tournament matches - teams play stronger at home. </p>
<p class = "text-justify"> Offseason Cup games are type B ("must") games, that is, they change player fatigue, non-players rest, heal injuries. </p>
<p class = "text-justify"> Read more about the tournament rules in a separate section - Offseason Cup. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "7"> 7. Amateur club conference (type B). </p>
<p class = "text-justify"> The Amateur Club Conference is a tournament for new League teams and teams that have not found a place in their national championships this season. New teams join the conference draw automatically as soon as they register in the League and can start playing from any round until the end of the tournament. </p>
<p class = "text-justify"> The tournament is played on the same system as the offseason cup. </p>
<p class = "text-justify"> There is a home bonus in tournament matches - teams play stronger at home. </p>
<p class = "text-justify"> Games of the conference of amateur clubs are games of type B ("compulsory"), that is, they change the fatigue of the players, non-players - rest, heal injuries. This applies only to the teams that participate in the conference, the other teams (i.e. teams playing in the championships of their countries) are not affected by this tournament. </p>
<p class = "text-justify"> Read more about the tournament rules in a separate section - Amateur Clubs Conference. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "8"> 8. World Championship (type C). </p>
<p class = "text-justify"> This is a tournament for national teams, which includes the best players of each nationality. The best club managers can also become national team coaches, become the world champion with the national team of their country, perhaps the highest achievement in the League. </p>
<p class = "text-justify"> The World Championship regulations are determined for each season separately and may change from season to season. The World Championship regulations for a particular season can be found in a separate section of the rules. </p>
<p class = "text-justify"> All World Cup matches are "side" matches (type C). </p>
<p class = "text-justify"> Read more about the rules, terms and conditions of the World Cup in a separate section of the rules. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'What tournaments can I participate in?',
];
