<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#1.1"> 1.1. What are player positions. </a>
<br/>
<a href="#1.2"> 1.2. Align positions. </a>
<br/>
<a href="#2"> 2. Profile positions of players. </a>
<br/>
<a href="#2.1"> 2.1. P - Prop. </a>
<br/>
<a href="#2.2"> 2.2. H - Hooker. </a>
<br/>
<a href="#2.3"> 2.3. L - Lock. </a>
<br/>
<a href="#2.4"> 2.4. FL - Flanker. </a>
<br/>
<a href="#2.5"> 2.5. 8 - Number 8. </a>
<br/>
<a href="#2.6"> 2.6. SH - Scrum-half. </a>
<br/>
<a href="#2.7"> 2.7. FH - Fly-half. </a>
<br/>
<a href="#2.8"> 2.8. W - Wing. </a>
<br/>
<a href="#2.9"> 2.9. C - Center. </a>
<br/>
<a href="#2.10"> 2.10. FB - Fullback. </a>
</p>
<p class = "strong text-justify" id = "1"> 1. General provisions. </p>
<p class = "text-justify" id = "1.1"> <span class = "strong"> 1.1. What are the positions of the players. </span> Each player in the League has one or two profile (favorite) positions: </p>
<ul>
<li> the rugby player plays in his own strength in his profile positions; </li>
<li> the rugby player plays weaker in non-core positions. </li>
</ul>
<p class = "text-justify"> Profile positions can be trained to players at the team\'s training center. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "1.2"> <span class = "strong"> 1. 2. Alignment of positions. </span> The presence of two profile positions in a player is called alignment of positions. </p>
<p class = "text-justify"> If a player has two profile positions, he can play any of these positions without losing his strength. </p>
<p class = "text-justify"> All players can have the second position. </p>
<p class = "text-justify"> The maximum number of positions per player is two. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "2"> 2. Profile positions of players. </p>
<p class = "text-justify" id = "2.1"> <span class = "strong"> 2.1. PR - Prop. </span> </p>
<p class = "text-justify"> Prop position can be played by: </p>
<ul>
<li> PR (Prop) with 100% real power; </li>
<li> H (Hooker), L (Lock), FL (Flanker), 8 (Number 8) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.2"> <span class = "strong"> 2.2. H - Hooker. </span> </p>
<p class = "text-justify"> Hooker positions can be played by: </p>
<ul>
<li> H (Hooker) with 100% real strength; </li>
<li> P (Prop), L (Lock), FL (Flanker), 8 (Number 8) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.3"> <span class = "strong"> 2.3. L - Lock. </span> </p>
<p class = "text-justify"> Lock positions can be played by: </p>
<ul>
<li> L (Lock) with 100% real strength; </li>
<li> P (Prop), H (Hooker), FL (Flanker), 8 (Number 8) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.4"> <span class = "strong"> 2.4. FL - Flanker. </span> </p>
<p class = "text-justify"> Flanker positions can be played by: </p>
<ul>
<li> FL (Flanker) with 100% real strength; </li>
<li> P (Prop), H (Hooker), L (Lock), 8 (Number 8) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.5"> <span class = "strong"> 2.5. 8 - Number 8. </span> </p>
<p class = "text-justify"> Position Number 8 can be played by: </p>
<ul>
<li> 8 (Number 8) with 100% real strength; </li>
<li> P (Prop), H (Hooker), L (Lock), FL (Flanker) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.6"> <span class = "strong"> 2.6. SH - Scrum-half. </span> </p>
<p class = "text-justify"> The Scrum-half positions can be played by: </p>
<ul>
<li> SH (Scrum-half) with 100% real strength; </li>
<li> FH (Fly-half), W (Wing), C (Center), FB (Fullback) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.7"> <span class = "strong"> 2.7. FH - Fly-half. </span> </p>
<p class = "text-justify"> Fly-half positions can be played by: </p>
<ul>
<li> FH (Fly-half) with 100% real strength; </li>
<li> SH (Scrum-half), W (Wing), C (Center), FB (Fullback) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.8"> <span class = "strong"> 2.8. W - Wing. </span> </p>
<p class = "text-justify"> Wing positions can be played by: </p>
<ul>
<li> W (Wing) with 100% real strength; </li>
<li> SH (Scrum-half), FH (Fly-half), C (Center), FB (Fullback) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.9"> <span class = "strong"> 2.9. C - Center. </span> </p>
<p class = "text-justify"> The Center position can be played by: </p>
<ul>
<li> C (Center) with 100% real strength; </li>
<li> SH (Scrum-half), FH (Fly-half), W (Wing), FB (Fullback) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.10"> <span class = "strong"> 2.10. FB - Fullback. </span> </p>
<p class = "text-justify"> Fullback can be played by: </p>
<ul>
<li> FB (Fullback) with 100% real strength; </li>
<li> SH (Scrum-half), FH (Fly-half), W (Wing), C (Center) with 90% real strength; </li>
<li> Players in other positions with 80% real strength. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Player positions',
];
