<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. How do I get a command? </a>
<br/>
<a href="#1.1"> 1.1. Free teams. </a>
<br/>
<a href="#1.2"> 1.2. Manage multiple teams. </a>
<br/>
<a href="#2"> 2. Frequently asked questions. </a>
<br/>
<a href="#2.1"> 2.1. What is a new team? </a>
<br/>
<a href="#2.2"> 2.2. How are commands issued? </a>
<br/>
<a href="#2.3"> 2.3. I was recommended by the president of the federation, but I was not given a command. </a>
<br/>
<a href="#2.4"> 2.4. How do I get another command? </a>
<br/>
<a href="#2.5"> 2.5. I want to transfer / exchange commands with another manager, how to do it? </a>
</p>
<p class = "strong text-justify" id = "1"> 1. How do I get a command? </p>
<p class = "text-justify"> You can get a team in the League in the following way: </p>
<p class = "text-justify" id = "1.1"> <span class = "strong"> 1.1. Free teams. </span> You can take one of the already created teams, which for one reason or another was left without a manager - such teams are called free. </p>
<p class = "text-justify"> Select a command, click on the icon to go to the page for managing it, click on the button "Submit a request to manage this command to the moderator." </p>
<p class = "text-justify"> Several managers can apply for each of the free teams at once. The moderator selects from the applications for each team the manager who, in our opinion, needs this team the most at the moment. </p>
<p class = "text-justify"> An application can be reviewed in a period from a few seconds to several days. Moreover, if your applications constantly hang for a long time and to no avail without consideration, then most likely we are generally against giving you a command (someone is already playing in the League from your computer, you have too many commands, you have previously been seen in fraud, negative reputation, etc.) </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "1.2"> <span class = "strong"> 1.2. Managing multiple teams. </span> The site allows you to manage two teams at once if a number of conditions are met: </p>
<ul>
<li> all your teams must be managed from one login, registration of two logins per person is prohibited; </li>
<li> it is forbidden to play by several teams in the same country; </li>
<li> it is forbidden to carry out transactions and organize matches between their teams; </li>
<li> if the draw brings the teams of one manager in a match against each other in the Champions League, the manager should not play an agreement (catch himself in a collision, set only one of the teams to rest, play base-versus-double and carry out other actions that the scouts can be defined as aimed at achieving a certain result in favor of a specific team). It is allowed to play with both super teams or both.
</ul>
<p class = "text-justify"> Each manager has a profile with the maximum number of commands that he can manage at the same time. Regular managers can only manage one team, VIP managers can take control of a second team. </p>
<p class = "text-justify"> Purchasing a VIP Club membership does not guarantee a manager a free team out of turn. Commands are received on a general basis. </p>
<p class = "text-justify"> If a manager has more than the maximum number of teams allowed, the "extra" clubs are automatically put into vacant clubs. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "2"> 2. Frequently asked questions. </p>
<p class = "text-justify" id = "2.1"> <span class = "strong"> 2.1. What is a new team. </span> A new team is a team that is just starting its way in the Virtual Rugby League. She hasn\'t played a game yet, you are her first coach. </p>
<p class = "text-justify"> In the new command: </p>
<ul>
<li> 30 rugby players of different ages; </li>
<li> stadium with a capacity of 100 seats; </li>
<li> 1 million rolls (our virtual money) in the account; </li>
<li> base level 1 without buildings; </li>
<li> 5 free base improvements; </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.2"> <span class = "strong"> 2.2. What is the principle of the distribution of teams? </span> In the League, the priority is given to managers who do not have teams, such applications are considered first. Also noteworthy are applications from the recommendations of the presidents of the federation. The rest of the applications are considered in case of a large number of free teams. In this case, VIP managers get priority. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.3"> <span class = "strong"> 2.3. I was recommended by the president of the federation, but I was not given a command? </span> The recommendation of the president of the federation is not a guarantee of getting a command. But such an application must be paid attention to, and in most cases of refusal, the main reason is the fact that the manager either cannot get a team in this particular federation, or, in principle, at the moment the administration is against receiving a team for him. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.4"> <span class = "strong"> 2.4. How to get another team? </span> The only way to get another team is to get a VIP Club membership and apply for a second team. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.5"> <span class = "strong"> 2.5. I want to transfer / exchange commands with another manager, how to do this? </span> You need to go to the page and select the manager to whom you want to transfer the command, indicate whether it is an exchange or just a transfer. The manager will receive a message about your offer and will be able to refuse or confirm it. </p>
<p class = "text-justify"> The automatic system will check the ability to transfer / exchange your command and, if necessary, indicate the reasons why the transfer / exchange cannot take place. You can refuse to transfer / exchange the club only before confirmation of the application by another manager, after the transfer / exchange of the team, claims and objections will not be accepted. </p>
<p class = "text-justify"> If the second manager does not respond to the offer, after a week it will be automatically canceled. Also, those offers will be automatically canceled that can no longer take place, for example, due to a change of manager in one of the teams from the application. </p>
<p class = "text-justify"> Technical support will not deal with other transfer and exchange options that are not provided by the automation. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'How do I get the command?',
];
