<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. What are special abilities and how to get them. </a>
<br/>
<a href="#2"> 2. List of special features. </a>
<br/>
<a href="#2.1"> 2.1. Strength (Sl). </a>
<br/>
<a href="#2.2"> 2.2. Pass (Ps). </a>
<br/>
<a href="#2.3"> 2.3. Combination (Km). </a>
<br/>
<a href="#2.4"> 2.4. Scrum (Cx). </a>
<br/>
<a href="#2.5"> 2.5. Leader (L). </a>
<br/>
<a href="#2.6"> 2.6. Athleticism (At). </a>
<br/>
<a href="#2.7"> 2.7. Speed ​​(Sk). </a>
<br/>
<a href="#2.8"> 2.8. Capture (Zx). </a>
<br/>
<a href="#2.9"> 2.9. Cancer (Rk). </a>
<br/>
<a href="#2.10"> 2.10. Mol (Ml). </a>
<br/>
<a href="#2.11"> 2.11. Idol (Km). </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. What are special abilities and how to get them. </span> Each rugby player can have from zero to four special abilities (special skills, special abilities, specials), which give them certain bonuses under different conditions. </p>
<p class = "text-justify"> A player with special abilities is more useful to the team and appreciated higher - all special abilities give additional game benefits to their owners. </p>
<p class = "text-justify"> Each of the four possible special abilities for one player can be of four levels: from the first to the fourth. The higher the level of special ability, the greater the bonus it gives. </p>
<p class = "text-justify"> Accessibility is available at the team-based training center. </p>
<p class = "text-justify"> One training session either trains a new special ability, or increases the level of an existing special. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. A list of special abilities. </span> Players may have the following special abilities: </p>
<p class = "text-justify" id = "2.1"> <span class = "strong"> 2.1. Strength (DC). </span> Players with this special ability play better in strength martial arts. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-25"> Level </th> <th class = "col-25"> down the middle </th> <th class = "col-25"> 10 man rugby </ th> <th class = "col-15"> Others </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> <td class = "text-center"> + 3% strength </td> <td class = "text-center"> + 4% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> <td class = "text-center"> + 6% strength </td> <td class = "text-center"> + 8% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> <td class = "text-center"> + 9% strength </td> <td class = "text-center"> + 12% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> <td class = "text-center"> + 12% strength </td> <td class = "text-center"> + 16% strength </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.2"> <span class = "strong"> 2.2. Pass (Ps). </span> Players with this special ability are better at passing passes. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-25"> Level </th> <th class = "col-25"> 15 man rugby </th> <th class = "col-25"> champagne rugby </ th > <th class = "col-15"> Others </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> <td class = "text-center"> + 3% strength </td> <td class = "text-center"> + 4% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> <td class = "text-center"> + 6% strength </td> <td class = "text-center"> + 8% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> <td class = "text-center"> + 9% strength </td> <td class = "text-center"> + 12% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> <td class = "text-center"> + 12% strength </td> <td class = "text-center"> + 16% strength </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.3"> <span class = "strong"> 2.3. Combination (Km). </span> Players with this special ability perform better game combinations. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-25"> Level </th> <th class = "col-25"> champagne rugby </th> <th class = "col-25"> down the middle </ th > <th class = "col-15"> Others </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> <td class = "text-center"> + 3% strength </td> <td class = "text-center"> + 4% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> <td class = "text-center"> + 6% strength </td> <td class = "text-center"> + 8% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> <td class = "text-center"> + 9% strength </td> <td class = "text-center"> + 12% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> <td class = "text-center"> + 12% strength </td> <td class = "text-center"> + 16% strength </td> </tr>
</table> </table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.4"> <span class = "strong"> 2.4. Skirmish (Cx). </span> Players with this special ability play better in skirmishes. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-25"> Level </th> <th class = "col-25"> 10 man rugby </th> <th class = "col-25"> 15 man rugby </ th> <th class = "col-15"> Others </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> <td class = "text-center"> + 3% strength </td> <td class = "text-center"> + 4% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> <td class = "text-center"> + 6% strength </td> <td class = "text-center"> + 8% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> <td class = "text-center"> + 9% strength </td> <td class = "text-center"> + 12% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> <td class = "text-center"> + 12% strength </td> <td class = "text-center"> + 16% strength </td> </tr>
</table> </table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.5"> <span class = "strong"> 2.5. Leader (L). </span> When a player with this special ability enters the starting lineup, the real strength of all players on his team entering the field increases by several percent. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-50"> Level </th> <th> Bonus </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 0.5% strength for each player on their team </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 1% strength for each player on their team </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 2% strength for each player on their team </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 3% strength for each player on their team </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.6"> <span class = "strong"> 2.6. Athleticism (At). </span> Players with this special ability get less tired after matches. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-50"> Level </th> <th> Bonus </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> 1% less fatigue after playing a match </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> 2% less fatigue after playing a match </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> 3% less fatigue after playing a match </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> 4% less fatigue after playing a match </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.7"> <span class = "strong"> 2.7. Speed ​​(Sk). </span> Players with this special ability move faster across the field. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-50"> Level </th> <th> Bonus </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.8"> <span class = "strong"> 2.8. Capture (Zx). </span> Players with this special ability are better at capturing opponents. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-50"> Level </th> <th> Bonus </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.9"> <span class = "strong"> 2.9. Cancer (Rk). </span> Players with this special ability are better at playing cancer. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-50"> Level </th> <th> Bonus </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.10"> <span class = "strong"> 2.10. Mole (Jr). </span> Players with this special ability play better at maul. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-50"> Level </th> <th> Bonus </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% strength </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% strength </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% strength </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% strength </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.11"> <span class = "strong"> 2.11. Idol (C). </span> Players with this special ability attract more spectators to the stands. </p>
<table class = "table table-hover table-bordered">
<tr> <th class = "col-50"> Level </th> <th> Bonus </th> </tr>
<tr> <td class = "text-center"> 1 </td> <td class = "text-center"> + 5% viewers </td> </tr>
<tr> <td class = "text-center"> 2 </td> <td class = "text-center"> + 10% viewers </td> </tr>
<tr> <td class = "text-center"> 3 </td> <td class = "text-center"> + 15% viewers </td> </tr>
<tr> <td class = "text-center"> 4 </td> <td class = "text-center"> + 20% viewers </td> </tr>
</table>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Player special abilities',
];
