<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Players from the League. </a>
</p>
<p class = "strong text-justify" id = "1"> 1. General provisions. </p>
<p class = "text-justify"> One of the main functions of a manager is to send his team line-up to all matches on the schedule. </p>
<p class = "text-justify"> A match application is 15 players, coaching instructions on how to play. </p>
<p class = "text-justify"> If the squad was not sent on time for the match specified in your team\'s schedule, then those players of your team who will be selected by our program will enter the field. The lineups of free teams are determined in the same way. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "2"> 2. Players from the League. </p>
<p class = "text-justify"> If you don\'t have enough players on your team, you can leave some players empty. In this case, you can invite a certain number of additional players from the League to your team during the match, which will take empty spaces in the application. The strength of such players is 15, fatigue 0%, no special abilities, do not affect chemistry, form 100%. </p>
<p class = "text-justify"> The number of players from the League is unlimited. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Team line-up for the match',
];
