<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. What are player injuries? </a>
<br/>
<a href="#2"> 2. Types of injuries. </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. What are player injuries? </span> Any rugby player can be injured as a result of the game. An injured player cannot participate in matches, highlighted in red in the roster. Player injuries are completely healed at the end of the season. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. Types of injuries. </span> Injuries are conventionally divided into micro (1-2 days), light (3-4 days), severe (5-6 days) and very severe (7-9 days). </p>
<p class = "text-justify"> All injuries are discovered after the game. The virtual rugby player plays out the match to the end without losing strength, however, upon returning to the base, he is injured and is subject to treatment. The likelihood of injury depends entirely on the player\'s fatigue. The larger it is, the more likely it is to get a post-match injury. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Player Injury',
];
