<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Reasons for placing teams on vacant. </a>
<br/>
<a href="#2.1"> 2.1. By auto trains. </a>
<br/>
<a href="#2.2"> 2.2. The manager hasn\'t joined the team for a long time. </a>
<br/>
<a href="#2.3"> 2.3. Extra commands. </a>
<br/>
<a href="#2.4"> 2.4. Submitting to free moderators. </a>
<br/>
<a href="#3"> 3. How can I avoid putting my team on vacant? </a>
<br/>
<a href="#4"> 4. How do I get a command back? </a>
<br/>
<a href="#5"> 5. What can happen to free teams? </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. General provisions. </span> A team placed in vacant is considered to have lost its coach for one reason or another. While the team is among the free, its coach cannot manage it even if he enters his username and password. To prevent your team from being free, it is enough to continue to play, while not committing shenanigans. During vacations or other technical difficulties, you must tick the "on vacation" checkbox in your personal data, you can find deputies so that your team is not left unattended for a long time. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "2"> 2. Reasons for placing teams on free. </p>
<p class = "text-justify" id = "2.1"> <span class = "strong"> 2.1. By autos. </span> The team plays 5 autos in a row with this manager. </p>
<p class = "text-justify"> Autocomplies are not counted when a manager is on vacation or under another manager. At the VIP-manager, the teams for the auto trains are not assigned to the free ones. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.2"> <span class = "strong"> 2.2. The manager has not joined the team for a long time. </span> Even if the team does not participate in tournaments, there are always some things to do, if the manager does not do anything in the team and does not even enter, then he does not need the team. </p>
<p class = "text-justify"> The loss of a manager is allowed for a maximum of 15 days in a row. For a VIP manager, this period is 60 days. </p>
<p class = "text-justify"> Naturally, this does not apply to managers who have the "on vacation" checkbox checked - during the vacation, teams for the absence of a manager are not put into free ones. </p>
<p class = "text-justify"> If the manager was on vacation, then he should visit all his teams to be beyond suspicion of a long absence. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.3"> <span class = "strong"> 2.3. Extra teams. </span> If the manager has more teams than he is allowed to manage at the moment (the younger ones are added to the free ones by the time they get into control). </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2.4"> <span class = "strong"> 2.4. Submitting to vacant by a moderator. </span> There are reasons why a moderator can send commands to vacant: </p>
<ul>
<li> fraud (usually malicious) - applies to VIP teams as well; </li>
<li> managing multiple teams in the same division (in the same country) - applies to VIP teams as well; </li>
<li> gross, systematic, intentional violation of the rules of the game and behavior on the site - applies to VIP teams as well; </li>
<li> The site administration has the right to remove the manager from managing his teams if the manager, by his actions or inaction, violates the agreement on the use of the site - this also applies to VIP managers. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. How can I avoid putting my team on the free list? </span> The most correct recommendation is to regularly send squads to matches, participate in team management - this is the point of your participation in the Virtual Rugby League. Do not participate in fraudulent activities. </p>
<p class = "text-justify"> If you need to leave and there is a risk that you will not be able to visit the site for a long time - be sure to check the box "I went on vacation" in your personal data. Thus, you can take a break from the site without consequences. </p>
<p class = "text-justify"> The vast majority of managers never "lose" their teams. If your team is in free (and if even several times), then something is going wrong - perhaps you are not interested in the Virtual Rugby League or there is not enough free time. In this case, it is better to send the teams to the free ones yourself. </p>
<p class = "text-justify"> Another option to avoid putting your team on the free list is to join the VIP club. VIP-managers\' teams are not set free even in the case of a long absence of the coach for no reason. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4"> <span class = "strong"> 4. How to get the team back? </span> If your team is vacant due to auto-composition or a long absence from the site and your team has not yet received a new coach, you just need to click the button "I want to continue to manage this team" - this you confirm that you are still with us and wish to continue to be the manager of this team. </p>
<p class = "text-justify"> If the team is in free for violating the rules of the site, then its return is impossible. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "5"> <span class = "strong"> 5. What can happen to free teams? </span> With free teams, the League has the right to do the following: </p>
<ul>
<li> send squads to matches (auto-squads); </li>
<li> build and destroy base and stadiums; </li>
<li> buy and sell players on the transfer market; </li>
</ul>
<p class = "text-justify"> Free teams unclaimed for a long time can be re-registered by the League. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'What are the free teams for?',
];
