<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Growing strength of young players. </a>
<br/>
<a href="#3"> 3. Veterans lose their strength. </a>
<br/>
<a href="#4"> 4. Retirement. </a>
<br/>
<a href="#5"> 5. Monetary compensation for a veteran. </a>
<br/>
<a href="#6"> 6. Command bases. </a>
<br/>
<a href="#7"> 7. National team players. </a>
<br/>
<a href="#8"> 8. Injuries. </a>
<br/>
<a href="#9"> 9. Rented players. </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. General. </span> At the end of the season, young players (from 17 to 23 years old inclusive) progress in strength, while veterans (from 31 to 35 years old inclusive) lose strength. </p>
<p class = "text-justify"> Hereinafter, we mean the age of the player with which he spends the ending season. All players (from 17 to 34 years old inclusive) will spend the next season "aging" by a year (for example, a 24-year-old player in the next season will be 25 years old). All players aged 35 will retire (retire) at the end of the season. </p>
<p class = "text-justify"> In the League, the youngest players are 17 years old, the oldest players are 35 years old. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. Growth of strength of young players. </span> At the end of the season, young players add the following number of points to strength by maturing one year: </p>
<ul>
<li> 17 years old receive +10 strength points; </li>
<li> 18 years old receive +9 strength points; </li>
<li> 19 years old receive +8 strength points; </li>
<li> 20 years old gain +7 strength points; </li>
<li> 21 years old gain +6 strength points; </li>
<li> 22 years old gain +5 strength points; </li>
<li> 23 years old receive +4 strength points. </li>
</ul>
<p class = "text-justify"> The rest do not grow at the end of the season. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. Veterans lose their strength. </span> At the end of the season, veterans lose the following points: </p>
<ul>
<li> 31 years old - 5%; </li>
<li> 32 years old - 10%; </li>
<li> 33 years old - 15%; </li>
<li> 34 years old - 20%; </li>
<li> 35 years old - retirement. </li>
</ul>
<p class = "text-justify"> Please note that if the strength of young players grows by a strictly defined number of points (i.e., for example +2 points), then the old players lose the percentage of their points (i.e. .e. for example 10%). </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4"> <span class = "strong"> 4. Retirement. </span> All players 35 years old at the beginning of the season announce their desire to retire. These players are marked with a special badge and play the last season. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "5"> <span class = "strong"> 5. Monetary compensation for a veteran. </span> For absolutely all veterans who end their careers in the current season in any team, compensation in the amount of 50% of their nominal value is entitled. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "6"> <span class = "strong"> 6. Team bases. </span> At the end of the season, construction and training ends according to the construction and training rules. It is believed that a fairly large virtual time passes between the end of the season and the beginning of the next one. At the beginning of the season, all the buildings and base of the team are in working order, there is no one in training. </p>
<p class = "text-justify"> The number of workouts done at the start of the season is reset to zero. Unused workouts will not be carried over to the new season. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "7"> <span class = "strong"> 7. National team players. </span> All national team players return to their teams before aging and other activities and are no different from other players. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "8"> <span class = "strong"> 8. Injuries. </span> It is believed that there is enough virtual time between the end of the season and the beginning of the next to heal injuries. At the beginning of the season, all players\' injuries are reset to zero. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "9"> <span class = "strong"> 9. Loaned players. </span> If at the end of the season a player is on loan, then at the beginning of the new season he will continue to play for the team that rented him. The lease term remains the same as it was at the end of the season. </p>
<p class = "text-justify"> The rented player gets tired from the team that rented him at the start of the season. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'What happens at the end of the season?',
];
