<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. What is team re-registration? </a>
<br/>
<a href="#2"> 2. How to start re-registration? </a>
<br/>
<a href="#3"> 3. Reasons for refusal to re-register. </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. What is team re-registration? </span> If the team you have inherited is in a hopeless state, and to such an extent that its prospects are even less than that of the new one, you can go through the club re-registration procedure. Re-registration is also possible if you are not at all satisfied with what its previous manager did with the team. </p>
<p class = "text-justify"> Re-registration is an opportunity to start a team\'s life from scratch(although the team\'s results will remain in its history). This is an opportunity to transform a hopeless club into a new one, i.e. having: </p>
<ul>
<li> 30 rugby players of different ages; </li>
<li> stadium with a capacity of 100 seats; </li>
<li> 10 million rolls (our virtual money) in the account; </li>
<li> a level 1 base without buildings. </li>
<li> 5 free base improvements; </li>
</ul>
<p class = "text-justify"> Upon re-registration, all players on a team become new players who have not played a single minute of playing time for that team. </p>
<p class = "text-justify"> The physical form of all team players upon re-registration is determined randomly. </p>
<p class = "text-justify"> The fatigue of all team members is equal to 50%. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. How to start re-registration? </span> If you have decided to re-register your club, then you need to go to it, go to the "Personal data" page (graphical button with a passport). There is a button "Re-register command" leading to the page for starting the re-registration procedure. </p>
<p class = "text-justify"> This page will tell you the reasons why re-registration of the command is not possible, or will ask you to confirm your intentions to re-register the command. </p>
<p class = "text-justify"> If the automation allowed your team to re-register and you have successfully confirmed your intentions, then your team will go through the re-registration procedure and there will be no way back. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. Reasons for refusing to re-register. </span> You cannot re-register a team if: </p>
<ul>
<li> there are players in the transfer or rental market or there are applications for purchase / rent; </li>
<li> the team made trades, the verification of which has not been completed yet; </li>
<li> the team has players on loan from another team; </li>
<li> there are players on the loaned team; </li>
<li> there are national team players in the team; </li>
<li> the team base has already reached the fifth level; </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Team re-registration',
];
