<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Who can you play with? </a>
<br/>
<a href="#3"> 3. When can I play? </a>
<br/>
<a href="#4"> 4. Restrictions and prohibitions. </a>
<br/>
<a href="#5"> 5. Stadium, money and spectators. </a>
</p>
<p class = "strong text-justify" id = "1"> 1. General provisions. </p>
<p class = "text-justify"> A friendly match is a practice match between the two teams, organized by the managers of the two participating teams, to practice, test tactics, or simply to find out which team is stronger. </p>
<p class = "text-justify"> A Friendly Match may or may not be played. You choose your opponent yourself, send him an invitation to a specific game day and wait for a response. If the answer is yes, a friendly match will be organized. </p>
<p class = "text-justify"> If a match is organized - it is included in the teams\' schedule and will take place in any case, it cannot be canceled . if there are no lineups for one or both teams for this match, the generator will create auto - lineups . </p >
<p class = "text-justify"> In friendlies, all players play with the same 25 % fatigue and 100 % fitness . </p >
<p class = "text-justify"> Fatigue of players in friendly matches does not change(does not increase for players and does not decrease for vacationers). The columns IP(played in a row) and OP(rested in a row) are not affected by the holding of a friendly match(they do not change). </p >
<p class = "text-right text-size-3" > [<a href = "#0" > to content </a >] </p >
<p class = "text-justify" id = "2" > <span class = "strong" > 2. Who can I play with ? </span > Friendly matches can be played by any teams registered in the League, having previously agreed and received each other\'s consent to organize the game. </p>
<p class = "text-justify"> You can only negotiate a friendly game with a team that is more or less equal in strength to yours (otherwise, the team you just need will not be listed on the friendly matches organization page). </p>
<p class = "text-justify"> For convenience, you can set one of three statuses in each of your commands: </p>
<ul>
<li> regular status - does not distinguish your team from the crowd. You yourself will choose whether to send or accept invitations from other teams, reject every proposal that comes up or agree; </li>
<li> status for those who like to play friendlies - in which the first offer sent to your team will be automatically accepted; </li>
<li> I don’t play friendlies - a status whereby you will not be annoyed by invitations to play a friendly match. </li>
</ul>
<p class = "text-justify"> You cannot keep more than five open sentences at the same time for one day. It is necessary to wait for the reaction to the offer to play (positive or negative) before offering to play another (sixth, etc.) team. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. When can I play? </span> Friendly matches can only be organized on specially designated match days marked in the schedule as "Friendly Match". </p>
<p class = "text-justify"> Agree on a friendly match only for the next game days. You cannot play more than one match on one match day. </p>
<p class = "text-justify"> You can agree on a friendly match no later than 24 hours before the game, so that both opponents have a chance to send their squads. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4"> <span class = "strong"> 4. Restrictions and prohibitions. </span> It is forbidden to organize friendly games in which the manager knows the exact composition of the opponent. It is forbidden to hold friendly games between teams of the same manager. </p>
<p class = "text-justify"> A maximum of 1 match can be played between two teams during a season. </p>
<p class = "text-justify"> Violation of the rules for organizing friendly matches entails penalties for teams, up to putting them on free. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "5"> <span class = "strong"> 5. Stadium, money and spectators. </span> Friendly matches are played at the stadium of the opponent who sent the invitation. However, there is no home bonus for the organizing team in friendlies. </p>
<p class = "text-justify"> The host of the match sets the cost of a friendly match ticket. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Friendlies',
];
