<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. What is the Virtual Rugby League? </a>
<br/>
<a href="#2"> 2. How to play and who is playing? </a>
<br/>
<a href="#3"> 3. How does the League work? </a>
<br/>
<a href="#4"> 4. How is the League governed? </a>
<br/>
<a href="#5"> 5. If you want to become a member of the game. </a>
<br/>
<a href="#6"> 6. If something is not in the rules. </a>
<br/>
<a href="#7"> 7. Let\'s live together! </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. What is Virtual Rugby League? </span> Virtual Rugby League - online virtual rugby manager is a game in which you have to manage your own rugby team. Here you will compete with hundreds of other members of the League, who are united by one word - rugby! </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. How to play and who is playing? </span> Our rugby manager is played via the Internet (must have access to the site virtual-rugby.com) and e-mail (each participant in the game must have a working mailbox). Anyone who has read the rules is allowed to participate in the League. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. How does the League work? </span> Each player participating in the League controls his own rugby team, which participates in virtual competitions along with other teams, also run by real people. The league plays by seasons. Each season consists of a large number of competitions, the main ones being national championships. The Champions League and World Championships are held during each season. Information about all tournaments of the current season can be found on the "Tournaments" page. The schedule of game days of the season (ie at what time of which matches are played) can be found on the "Schedule" page. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4"> <span class = "strong"> 4. How is the League governed? </span> The League and its games are governed by the League Administration. All documents on the "Rules" page are the League\'s game constitution, the rules of the game. The game currency in the League is a roll. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "5"> <span class = "strong"> 5. If you want to become a member of the game. </span> Your manager\'s career begins with registration on the site. At this point, you are a "manager without a team". </p>
<p class = "text-justify"> Then you take control of an already created club that does not have a coach. And then you become a full participant in the game. </p>
<p class = "text-justify"> To learn more about the registration process, first see the section "How to register and take a command?". </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "6"> <span class = "strong"> 6. If something is not in the rules. </span> If you have any questions, you can always ask technical support or leave a message in the forum in the most appropriate section. Even experienced managers may be able to clarify some questions for you, the League Administration will answer the rest. Gaps in the Rules will be regularly addressed. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "7"> <span class = "strong"> 7. Let\'s live together! </span> For dishonest play, for deliberate violations of the rules, for incorrect behavior, for destructive actions on the website, the League Administration has the right to impose fines, in extreme cases the violator may lose his team. The Administration of the League has the right to restrict especially zealous violators from visiting the site and registering on it. Fixed matches can be canceled with the appointment of a technical defeat to one or both teams. Contractual transactions can be canceled. </p>
<p class = "text-justify"> If the violation is insignificant, especially if the violation may be caused by the violator\'s inexperience, the League Administration has the right to replace fines by issuing warnings. Each penalty or warning is accompanied by an indication of the violation. </p>
<p class = "text-justify"> The most serious violations in the League are: </p>
<ul>
<li> negotiated games and deals; </li>
<li> game under several nicknames (logins); </li>
<li> playing for several teams in one country; </li>
<li> deliberate misinformation of newcomers, spreading false information about the rules or news in the League; </li>
<li> insults to managers, visitors and the Administration of the League. </li>
</ul>
<p class = "text-justify"> For deliberate destruction of a team, the League Administration has the right to withdraw the team and punish the negligent manager. </p>
<p class = "text-justify"> Appeals to fines, cancellation of deals, withdrawal of teams and other penalties are considered in technical support. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'What is Virtual Rugby League?',
];