<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#2">2. Игроки от Лиги.</a>
</p>
<p class="strong text-justify" id="1">1. Общие положения.</p>
<p class="text-justify">Одна из основных функций менеджера - отправлять состав своей команды на все матчи, которые есть в расписании.</p>
<p class="text-justify">Заявка на матч - это 20 полевых игроков и два вратаря, тренерские указания, как именно им играть.</p>
<p class="text-justify">Если на матч, указанный в расписании игр вашей команды, не был вовремя отправлен состав, то на поле выйдут те игроки вашей команды, которых отберет наша программа. Точно так же определяются составы свободных команд.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2">2. Игроки от Лиги.</p>
<p class="text-justify">Если у вас недостаточно игроков в команде, вы можете оставить места некоторых игроков пустыми. В этом случае в вашу команду, на время матча можно пригласить некоторое число дополнительных игроков от Лиги, которые и займут пустые места в заявке. Сила таких игроков 15, усталость 0%, спецвозможностей нет, любимых стилей нет, не влияют на сыгранность и взаимопонимание, форма 100%.</p>
<p class="text-justify">Количество игроков от Лиги неограничено.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Состав команды на матч',
];
