<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Violations and restrictions. </a>
<br/>
<a href="#3"> 3. Punishments. </a>
<br/>
<a href="#4"> 4. Complaints to the moderator. </a>
<br/>
<a href="#5"> 5. Complaints about the actions of the moderators. </a>
</p>
<p class = "strong text-justify" id = "1"> 1. General provisions. </p>
<p class = "text-justify"> 1.1. The virtual-rugby.com forum is a private resource, part of the Virtual Rugby League. By using it, you agree to be guided by these Rules. Violators of the Rules are punished with warnings and can be blocked temporarily or permanently. </p>
<p class = "text-justify"> 1.2. The forum is post-moderated, i.e. messages are added immediately, and they are "decimated" later. </p>
<p class = "text-justify"> 1.3. Forum moderators keep order on the forum. </p>
<p class = "text-justify"> 1.3.1. Moderators exercise control over the forums, can edit, delete posts, close and move threads / posts to the appropriate / more appropriate section of the forum. </p>
<p class = "text-justify"> 1.3.2. Discussion of the actions of the moderators and the Rules of using the forum is prohibited everywhere, except in the topics specially intended for this: Complaints about the actions of the forum moderators and the Forum Rules. </p>
<p class = "text-justify"> 1.3.3. Forum moderators need to write private messages, and not write them directly in the topic about completely different things. </p>
<p class = "text-justify"> 1.3.4. Forum moderators have the right to preferential interpretation of certain points of the Forum Rules in case of statements about the presence of a double meaning in such points on the part of the user. </p>
<p class = "text-justify"> 1.4. All messages reflect the opinions of their authors, and the Administration does not bear any responsibility for them. If you think that any messages are against the law, contain commercial secrets or are capable of causing harm to someone, you can report this to the forum moderators. </p>
<p class = "text-justify"> 1.5. Adhere to the established culture of communication on our forum. We create our own habitat. Let\'s be polite and friendly to each other! If you see violations or are provoked to do so by other forum members, do not be led by the violators. You can write a letter to the forum administrator indicating the violation. The rest is the responsibility of the moderator. </p>
<p class = "text-justify"> 1.6. If you are new here, do not flatter yourself with the tone of some of the discussions. Many people have known each other for a long time and can afford such a tone towards each other. </p>
<p class = "text-justify"> 1.7. If you made a mistake, for example, duplicated a message, accidentally sent a response to the wrong place, or sent an empty message, then leave it as it is. Readers will figure it out, the moderator will clean it up later. If you really want to draw his attention to this, send him a private message. You shouldn\'t write new messages and comment on your mistakes, and then write messages apologizing for such a flood. </p>
<p class = "text-justify"> 1.8. When choosing an avatar, make sure that there is no similar avatar on the forum, otherwise the author, who had this avatar before, has the right to ask the administrator to remove the duplicate from your profile. </p>
<p class = "text-justify"> 1.9. Recommendations for creating new themes: </p>
<ul>
<li> Determine, by looking at the descriptions of each section, which one your theme is best suited to. </li>
<li> In the heading, be sure to state the essence of the matter briefly and without errors. </li>
<li> In the body of the message, provide a detailed description. </li>
</ul>
<p class = "text-justify"> 1.10. Recommendations for posting an answer to the topic: </p>
<ul>
<li> Read the topic header. </li>
<li> Avoid posting bulky materials copied from any web pages. Better post links to these materials. </li>
</ul>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "2"> 2. Violations and restrictions. </p>
<p class = "text-justify"> 2.1. It is forbidden to use rude, offensive and obscene expressions, website addresses, official nicknames (for example: Admin, Moderator) in the avatar and service profile fields, create avatars on political or religious topics. </p>
<p class = "text-justify"> 2.2. Re-registration is prohibited for any reason, especially if you set read-only mode for your nickname. </p>
<p class = "text-justify"> If for some unexplained reason you cannot participate in the forum under your main nickname, please contact technical support. </p>
<p class = "text-justify"> 2.3. The creation of the following topics is prohibited: </p>
<p class = "text-justify"> 2.3.1. Already discussed (discussed) or to which there are answers. Use the forum\'s  built-in search engine to find answers to your questions. </p>
<p class = "text-justify"> 2.3.2. In sections that are not relevant to the topic. If your topic does not correspond to the topic of any of the sections, write to the Offtopic forum. </p>
<p class = "text-justify"> 2.3.3. Having more than half of CAPITAL LETTERS in the title. Respect your interlocutors, they may think that you are yelling at them. </p>
<p class = "text-justify"> 2.3.4. Having decorations like "== - My theme - ==" in the name. </p>
<p class = "text-justify"> 2.3.5. Having little content (for example, "Help !!" or "Have a question") or a title that does not correspond to the content. </p>
<p class = "text-justify"> 2.3.6. With advertising of a player, team or tournament in all sections except the appropriate ones (Transfer / Rent / Registration and teams ...). Exceptions: It is allowed to write about players / teams in the national forums of the federation to which the player / team belongs. Note: It is allowed to create no more than one hot topic per team or tournament in any of the above sections. </p>
<p class = "text-justify"> All topics, the creation of which is prohibited by the above rules, can be closed or deleted by moderators without warning. </p>
<p class = "text-justify"> 2.4. It is forbidden to write messages containing: </p>
<p class = "text-justify"> 2.4.1. Appeals to violate the rules of the game, forum and legislation. </p>
<p class = "text-justify"> 2.4.2. Knowingly false information, slander, unsupported information that may harm someone\'s  reputation. Dishonest methods of conducting discussions in the form of "distorting" the statements of the interlocutors, editing their own messages in order to distort their original meaning are prohibited. </p>
<p class = "text-justify"> 2.4.3. Heavy-tone messages, obscene expressions and insults in any form. </p>
<p class = "text-justify"> 2.4.4. "Assaults" on individuals, groups of individuals, threats of physical violence, etc. </p>
<p class = "text-justify"> 2.4.5. Baseless claims that "this" is better and "this" is worse. If there are facts - good (mention it is your experience or someone else\'s ). No - don\'t forget to add that this is your personal opinion. </p>
<p class = "text-justify"> 2.4.6. Pointless or low-content information that does not carry a semantic load (flood) - for example, messages consisting of only emoticons, "+1" and the like. </p>
<p class = "text-justify"> 2.4.7. Excessive amount of grammatical errors, slang words, modern network "dialects". They tell forum visitors about your disrespectful attitude towards them. </p>
<p class = "text-justify"> 2.4.8. More than half of CAPITAL LETTERS. Respect your interlocutors, they may think that you are yelling at them. </p>
<p class = "text-justify"> 2.4.9. Content that is completely remote from the topic (malicious offtopic). </p>
<p class = "text-justify"> 2.4.10. A font with a size / color different from the default, unless you highlight a word or phrase if you want to emphasize their importance. </p>
<p class = "text-justify"> 2.4.11. Insulting fans of real teams in the form of various nicknames (such as "pigs", "horses", "homeless people", etc.), as well as any provocations addressed to the interlocutors that can cause a negative response. </p>
<p class = "text-justify"> 2.4.12. Abbreviations and allusions to common obscene and offensive language, such as "HZ", "PNH", etc. </p>
<p class = "text-justify"> 2.4.13. Motives of a nationalist or racist nature, as well as messages that discriminate against someone on the basis of age, gender, religion or social status. </p>
<p class = "text-justify"> 2.4.14. Quoting someone else\'s  message (including personal) containing words and expressions that are not allowed by the forum rules, without prior editing. </p>
<p class = "text-justify"> 2.4.15. Jokes about newcomers and other characters in the League that may be misunderstood. </p>
<p class = "text-justify"> 2.4.16. Persistently imposing your negative opinion on moderators, administrators or the League as a whole. </p>
<p class = "text-justify"> 2.4.17. Advertising a player, team or tournament in all topics and sections, except for the appropriate ones (Transfer / Rent / Registration and teams ...). Exceptions: It is allowed to post about players / teams in the national forums of the federation to which the player / team belongs. </p>
<p class = "text-justify"> 2.4.18. Over-quoting. This makes the message difficult to read and unnecessarily loads the topic. </p>
<p class = "text-justify"> 2.4.19. Any materials (and links to them) of a pornographic or erotic nature, scenes of violence, discussion of a political orientation; messages that violate a person\'s  right to privacy, as well as the publication of messages that are otherwise contrary to the laws and norms of morality. </p>
<p class = "text-justify"> 2.4.20. Spam (mass writing of any kind of advertisement or other type of messages) is prohibited. </p>
<p class = "text-justify"> 2.5. You should take into account the specifics of such a form of communication as a forum. In the forum, all messages are stored indefinitely. Therefore, in the forum it is customary to create messages that are not of momentary interest (especially only for individual participants), but messages that will be interesting to read to all visitors and some time after they are written. Personal correspondence in a general topic is considered offtopic. For personal correspondence there are private messages. </p>
<p class = "text-justify"> 2.6. It is forbidden to discuss the store and its users in a negative way, the sale / purchase of teams and players for real money. </p>
<p class = "text-justify"> 2.7. Personal showdowns and provocations on the forum are prohibited. </p>
<p class = "text-justify"> 2.8. It is forbidden to post links and references to other online rugby projects, as well as advertise other services and sites that are not related to the League, without the prior permission of the Administration (including in the signature). It is also forbidden to publish links to unlicensed commercial software (warez), programs for cracking it (cracks) and key generators, as well as to materials protected by copyright (books, music, videos, etc.). </p>
<p class = "text-justify"> 2.9. Messages in any language other than Russian (using the Russian alphabet) are prohibited. Users of the Russian-language forum should understand what other participants are writing. </p>
<p class = "text-justify"> 2.10. Unauthorized moderation is prohibited. Those. when a member of the forum, who is not a moderator of this forum, makes comments to other members. Use the "complaint" button. </p>
<p class = "text-justify"> 2.11. Users are prohibited from accepting the right to communicate on behalf of any (especially a banned or lost access to the forum) user. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "3"> 3. Punishments. </p>
<p class = "text-justify"> 3.1. A warning is issued in the event that the offender did not greatly violate the rules and at the same time might not have known about it (unintentionally). For three active warnings, the offender receives a minor fine. The warning is valid for 30 days. </p>
<p class = "text-justify"> 3.2. A small fine is issued for an intentional or rather serious violation, as well as for repeated violation of the same paragraph of the Rules. A small penalty puts the user into read-only mode. The minor penalty is valid for 3 days. </p>
<p class = "text-justify"> 3.3. A large fine is issued for a fairly serious deliberate violation, as well as for repeated violation of the same paragraph of the Rules and contempt for the actions of moderators. A large penalty, like a small one, puts the user in read-only mode. A large fine is valid for a week. </p>
<p class = "text-justify"> 3.4. Disqualification is issued for a very serious willful violation, for demonstrative hooliganism on the forum. Disqualification denies the user access to the forum for a week. </p>
<p class = "text-justify"> 3.5. The received punishments may, by decision, be accompanied by a monetary fine to the manager who commits deliberate and / or repeated violations of the forum rules and cannot be corrected. In case of particularly persistent opposition to the moderators, we have the right to ban the user on the forum or refuse to provide services to the violator on the site. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "4"> 4. Complaints to the moderator. </p>
<p class = "text-justify"> 4.1. Any active visitor to the forum can help the moderators by reporting violations of the rules of using the forum through complaints to the moderator. Moderators will be notified of your complaint and are required to respond to it. </p>
<p class = "text-justify"> 4.2. Authors of complaints should familiarize themselves with the opinion of the moderators about the message they left. It is forbidden to enter into disputes with moderators about the reaction to the complaint. You can send your possible disagreement with the actions of a particular moderator to technical support. </p>
<p class = "text-justify"> 4.3. Repeated writing of unfounded complaints is prohibited. Thus, you distract moderators from the really important work. In case of violation of this rule, moderators can punish the author of the complaint. </p>
<p class = "text-justify"> 4.4. Active and successful assistance to moderators through the system of writing complaints and assistance to newcomers on the forum is encouraged if an experienced manager wants to join the team of site and forum moderators. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "strong text-justify" id = "5"> 5. Complaints about the actions of the moderators. </p>
<p class = "text-justify"> 5.1. Any visitor to the forum can appeal against the punishment imposed on him personally by the moderators in a special topic on the forum "Complaints against the actions of moderators". In this thread, he will receive a response from the moderator. It is forbidden to enter into disputes with moderators after the final response of the moderators to the complaint. </p>
<p class = "text-justify"> 5.2. You can send your possible disagreement with the actions of a particular moderator to technical support. </p>
<p class = "text-justify"> 5.3. Repeated writing of unfounded complaints is prohibited. Thus, you distract moderators from the really important work. In case of violation of this rule, moderators can punish the author of the complaint. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Forum Terms of Use',
];
