<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id = "0"> Content </p>
<p class="text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Players and lineups. </a>
<br/>
<a href="#3"> 3. Substitution of players in the national team. </a>
<br/>
<a href="#4"> 4. National team coaches and their selections. </a>
<br/>
<a href="#5"> 5. Deputy coaches of the national teams and their election. </a>
<br/>
<a href="#6"> 6. Replacement of coaches and election of deputy coaches of the national teams. </a>
<br/>
<a href="#7"> 7. National team coaches prize money. </a>
<br/>
<a href="#8"> 8. Regulations. </a>
<br/>
<a href="#9"> 9. National team stadiums. </a>
<br/>
<a href="#10"> 10. Allocation of seats. </a>
<br/>
<a href="#11"> 11. Prize money. </a>
</p>
<p class="text-justify" id = "1"> <span class="strong"> 1. General provisions. </span> Along with various club tournaments in the League, there are also tournaments for the national teams of all federations. The World Championship among national teams is held once a season. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "2"> <span class="strong"> 2. Players and squads of teams. </span> A player with a nationality corresponding to this federation can become a player of a national team (in the League there is only one nationality for a player). </p>
<p class="text-justify"> Another additional condition for a player to be selected for the national team is that he must be included in the list of the best players of his federation according to his role in the League\'s opinion. be present on the page for applying for the squad, which is compiled automatically. This list includes a limited number of the best players in each position in our opinion. </p>
<p class="text-justify"> National team players cannot lose strength points, but they get tired and may get injured. For the participation of a player in the official match of the national team (entering the field) to the club to which he belongs at the time of the prize money, the prize money is awarded, the amount of which depends on the number of games of this rugby player for the national team. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "3"> <span class="strong"> 3. Substitution of players in the national team. </span> The coach of the national team can change the composition of the national team (from the list of the best players of the federation of his role according to the League). </p>
<p class="text-justify"> The selected team composition does not change when the national team coach is changed. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "4"> <span class="strong"> 4. Coaches of national teams and their election. </span> Any manager of the League can become a coach of the national team, who wants to become one, who has received a sufficient number of support votes when choosing the coaches of the national teams and at the same time is the manager of at least one team at the time of the election. The coach of each national team is selected once for the entire tournament. He is responsible for choosing the players for the national team, for sending the squads to the matches, for completing the assigned tasks, for achieving the promised goals. </p>
<p class="text-justify"> The initial selection of a national team coach is a two-step process: </p>
<p class="text-justify"> Stage one - collecting nominations. All candidates for national team coaches offer their lists of players whom they take to their national team, and draw up an electoral program - why they chose these players and what goals they plan to achieve. </p>
<p class="text-justify"> Only one team is allowed to lead. When accepting applications, it is allowed to be a candidate for only one national team, i.e. submit only one application. After that, even if he did not become a coach of any of the national teams, he can become a deputy coach of one of the teams in the federation where he took second place in the voting. </p>
<p class="text-justify"> Stage two - voting - looking at the programs and lists of selected players, managers determine by secret ballot - which of the candidates will be at the helm of the national team for the upcoming season. Each team owner from this federation has a 1 point vote. </p>
<p class="text-justify"> The winner of the vote is determined by a simple majority of the total rating. In case of equality of the total rating, the following parameters are taken into account in the final distribution of seats in voting in order of priority: </p>
<ul>
<li> rating of the selected squad; </li>
<li> candidate rating; </li>
<li> date of registration of the candidate in the League; </li>
</ul>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "5"> <span class="strong"> 5. National team deputy coaches and their election. </span> The national team deputy coach is determined during the initial head coach selection phase - this is the second-placed candidate during the voting. </p>
<p class="text-justify"> No manager can hold two different leadership positions for the national teams of the same season. </p>
<p class="text-justify"> The deputy coach has limited access to the management of the national team, i.e. can only send the squad to the match, which will take to the field in the event that the head coach does not send the squad to the match or allows the deputy to edit it. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "6"> <span class="strong"> 6. Replacement of coaches and election of deputy coaches of the national teams. </span> In the national team roster, any manager who manages a team from that federation can express his attitude towards the coach of the national team. The coach of the national team cannot evaluate himself. </p>
<p class="text-justify"> The resignation of a national team coach occurs if the following conditions are met: </p>
<ul>
<li> more than 25% of active federation managers will express a negative attitude towards the coach (active managers - this means that the opinion of managers of free teams is not taken into account at all, free teams do not take part in assessing the work of national team coaches in general); </li>
<li> the national team has a deputy. </li>
</ul>
<p class="text-justify"> Instead of the coach of the national team, if he is removed from office, his deputy will necessarily become the coach. Thus, a vacant position is formed for which applications are open. </p>
<p class="text-justify"> Only one team is allowed to lead. When accepting applications, it is allowed to be a candidate for only one national team, i.e. submit only one application. If you are already a coach or deputy of a national team, then you will not be able to apply. </p>
<p class="text-justify"> Not earlier than 24 hours after the opening of the application acceptance, if there is at least one candidate, voting for the post of the deputy of the national team opens. Voting takes place among the managers of the federation where the deputy of the national team is being elected. The vote of each team manager from this federation is worth 1 point. </p>
<p class="text-justify"> Voting will end no earlier than 48 hours after the start. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "7"> <span class="strong"> 7. National team coaches\' prize money. </span> The salary of the national team coaching staff is 20% of the money earned by the national team. </span> This amount is divided among all the coaches and deputies who managed the team throughout the tournament, in proportion to the number of days that the manager was in office. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "8"> <span class="strong"> 8. Regulations. </span> The World Championship is held for all national teams. National team matches are played in parallel with the championships and are type C games, i.e. playing players get tired, resting fatigue is not restored. </p>
<p class="text-justify"> The World Championship is played in a round robin system, with each team playing one match against everyone else. </p>
<p class="text-justify"> All teams for the qualifying round are given 2 super attitudes and 2 rests. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "9"> <span class="strong"> 9. National team stadiums. </span> National team matches are played at the largest stadium in the federation. The selection of the stadium occurs when the match is generated. </p>
<p class="text-justify"> National team matches do not have their own field. </p>
<p class="text-justify"> Ticket prices are determined by the host coach. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "10"> <span class="strong"> 10. Allocation of seats. </span> The following parameters are taken into account in the final distribution of seats in order of priority: </p>
<ul>
<li> accumulated tournament points (the more, the higher); </li>
<li> wins (the more, the higher); </li>
<li> draws (the more, the higher); </li>
<li> the difference in game points (the more, the higher); </li>
<li> of the accumulated game points (the more, the higher); </li>
<li> by Vs rating (the lower the higher); </li>
</ul>
<p class="text-justify"> If all of the above indicators are equal, a lot is drawn. </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class="text-justify" id = "11"> <span class="strong"> 11. Prize money. </span> According to the results of the championship, the teams receive prize money. </p>
<p class="text-justify"> National bonus prizes are calculated as follows: </p>
<p class="text-justify"> 25000000 * 0.98 ^ (place in the standings - 1) </p>
<p class="text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'World Championships',
];
