<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. General provisions. </a>
<br/>
<a href="#2"> 2. Tournament participants. </a>
<br/>
<a href="#3"> 3. Tournament regulations. </a>
<br/>
<a href="#4"> 4. Player fatigue. </a>
<br/>
<a href="#5"> 5. Prize money. </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. General. </span> The Champions League is the most prestigious club competition in the League, which includes the best teams from the previous season. The first Champions League draw will take place in Season 2. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. Tournament participants. </span> Champions League participants and the starting stage for each of them are determined according to the ranking of countries in the Champions League. </p>
<p class = "text-justify"> The higher a federation is in the ranking, the more places in the Champions League it gets, and the more its representatives start from later stages. </p>
<p class = "text-justify"> The exact number of participants and the starting stage for each of them can be found on the pages of the national federations. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. Tournament regulations. </span> The draw for the tournament is held at the beginning of the season and after each round played. Rounds are drawn by dividing the participants of each round into two or more baskets according to the Vs. indicator. </p>
<p class = "text-justify"> The tournament consists of the following stages: </p>
<p class = "text-justify"> 1) First qualifying round - two-round confrontation (teams play two matches: home and away). The winners advance to the second qualifying round. </p>
<p class = "text-justify"> 2) Second Qualifying Round is a two-round confrontation between the winners of the first qualifying round and the teams starting from the second qualifying round. The winners advance to the third qualifying round. </p>
<p class = "text-justify"> 3) Third Qualifying Round is a two-round confrontation between the winners of the second qualifying round and the teams starting from the third qualifying round. Winners advance to the play-off round. </p>
<p class = "text-justify"> 4) Group tournament - 8 groups of 4 teams, each team plays each in the group two matches: home and away. The winners of the third qualifying round and the teams starting from the group stage will participate. Each group will qualify for the 1/8 finals by the two best teams. </p>
<p class = "text-justify"> 5) 1/8 finals - a two-round confrontation in which the teams that took the first and second places in their groups in the group stage take part. The draw takes place according to the following scheme: </p>
<ul>
<li> A1 - B2 </li>
<li> C1 - D2 </li>
<li> E1 - F2 </li>
<li> G1 - H2 </li>
<li> B1 - C2 </li>
<li> D1 - E2 </li>
<li> F1 - G2 </li>
<li> H1 - A2 </li>
</ul>
<p class = "text-justify"> Winners advance to the quarter finals and are matched in pairs in the same order. </p>
<p class = "text-justify"> 6) 1/4 finals - a two-round confrontation in which the winners of the 1/8 finals take part. The winners advance to the 1/2 finals and are matched in pairs in the same order. </p>
<p class = "text-justify"> 7) 1/2 finals - a two-round confrontation in which the winners of the 1/4 finals take part. The winners advance to the final of the tournament. </p>
<p class = "text-justify"> 8) Finals - a two-round confrontation in which the winners of the 1/2 finals take part. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4"> <span class = "strong"> 4. Player fatigue. </span> Matches in this tournament are optional (type C), so the players who play rugby get a little tired, and the fatigue of those who did not participate in the match does not recover </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "5"> <span class = "strong"> 5. Prize money. </span> Champions League prize money can be found in the table: </p>
<table class = "table table-bordered table-hover">
<tr> <th> Place taken </th> <th> Prize money </th> </tr>
<tr> <td> Winner </td> <td class = "text-right"> $ 25,000,000 </td> </tr>
<tr> <td> Finalist </td> <td class = "text-right"> $ 23,000,000 </td> </tr>
<tr> <td> Semi-finals losers </td> <td class = "text-right"> $ 21,000,000 </td> </tr>
<tr> <td> Losers in quarter-finals </td> <td class = "text-right"> $ 19,000,000 </td> </tr>
<tr> <td> Losers in 1/8 finals </td> <td class = "text-right"> $ 17,000,000 </td> </tr>
<tr> <td> 3rd place in the group </td> <td class = "text-right"> 15,000,000 $ </td> </tr>
<tr> <td> 4th place in the group </td> <td class = "text-right"> $ 13,000,000 </td> </tr>
<tr> <td> Third qualifying round losers </td> <td class = "text-right"> $ 9,000,000 </td> </tr>
<tr> <td> Second qualifying round losers </td> <td class = "text-right"> $ 7,000,000 </td> </tr>
<tr> <td> First qualifying round losers </td> <td class = "text-right"> $ 5,000,000 </td> </tr>
</table>
<p class = "text-justify"> Prizes are also paid to those clubs that start playing from a certain stage and at the same stage and finish their performance. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'Champions League',
];
