<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify" id = "0"> Content </p>
<p class = "text-justify">
<a href="#1"> 1. Where am I? </a>
<br/>
<a href="#2"> 2. What\'s going on here? </a>
<br/>
<a href="#3"> 3. How do I start the game? </a>
<br/>
<a href="#4"> 4. How everything works here: </a>
<br/>
<a href="#4.1"> 4. 1. Matches. </a>
<br/>
<a href="#4.2"> 4. 2. Players. </a>
<br/>
<a href="#4.2"> 5. What else to read? </a>
</p>
<p class = "text-justify" id = "1"> <span class = "strong"> 1. Where am I? </span> You are on a rugby manager game site. Here, everyone manages their own rugby team, which participates in the championship of their country or conference of amateur clubs and in the Champions League - different teams, different competitions, different goals and opportunities. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "2"> <span class = "strong"> 2. What\'s going on here? </span> Here you are the coach and manager of your rugby team (or even several teams in different countries). </p>
<p class = "text-justify"> As a coach, you prepare players for matches, train and explore their hidden capabilities, monitor fatigue and physical fitness, prepare young people in a sports school, come up with tactics and strategy for each match. </ p >
<p class = "text-justify"> As a manager, you buy and sell players, rent out unnecessary ones, improve or reduce the team base and stadium, set ticket prices, organize friendly matches, keep track of the club\'s finances and development. </ p>
<p class = "text-justify"> All your actions are aimed at making your club more successful, richer and stronger than other participants in the game. Collect more trophies. Become popular in our rugby community. </p>
<p class = "text-justify"> Every team in our game (with the exception of those temporarily left without guidance) is controlled by a living person, and it\'s not so easy to play better than him! </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "3"> <span class = "strong"> 3. How to start the game? </span> Register on the site - everything is simple there, you can log in via social networks or come up with a username and password. On a special page, you can choose the team that you like best (read the section of the rules "How to get a team?") And that\'s all - you\'ve started the game! </p>
<p class = "text-justify"> Please note that the game is prohibited from playing with multiple accounts at the same time (multicasting is prohibited). </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4"> <span class = "strong"> 4. How does everything work here? </span> We make the game in such a way that you need no more than 20 minutes a day for the most necessary actions: send a request for the next match, schedule training and do something else from the necessary. Of course, if you are looking for the right player in the markets, or if you communicate, or make grandiose plans, you can spend the whole day in the game, but no more matches will be played from this. </p>
<p class = "text-justify"> We assume that you already know what rugby is, what rugby rules are and what rugby clubs are all about with their stadiums, bases, players of different strengths, profile positions and skills. Everything is about the same here. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4.1"> <span class = "strong"> 4. 1. Matches. </span> Almost every day your team plays one match (no more than one per day, but if you are not satisfied, you can manage several teams). You need to send a request from your team for each such match: </p>
<ul>
<li> select 15 players who are ready to play stronger than others at the moment </li>
<li> come up with tactics and strategy of the game in order to outwit the opponent and win </li>
</ul>
<p class = "text-justify"> You can read more about this in the section "How to send a squad for a match?" </p>
<p class = "text-justify"> The result of the match will be given to you after the generation of matches of the game day as a report. It will indicate: </p>
<ul>
<li> which players were selected for this match by each of the teams and what state they were in </li>
<li> which starting tactic was chosen by the coaches of both teams </li>
<li> how many viewers there were </li>
<li> how events developed in the match </li>
<li> what happened in the end - what score, who won, who entered attempts, who received cards and other statistics </li>
</ul>
<p class = "text-justify"> Yes, we don\'t have little people running around the screen and rugby players cannot be controlled with a joystick - we have a game about something else: </p>
<ul>
<li> about the tactics of the game in a particular match, which must be better than the opponent\'s in order to win. </li>
<li> about preparation for matches, when the coach plans in advance the fatigue, physical condition and teamwork of the players so that they will come up to the desired game in optimal condition. </li>
<li> about team development, thanks to which your club will receive more finance and stronger players than rivals. </li>
<li> about strategy throughout the entire season or even several, as a result of which it will be possible to win not only individual matches, but entire tournaments. </li>
</ul>
<p class = "text-justify"> After each match, the players change their fatigue, physical form, chemistry in accordance with the rules. Some players may gain or lose strength. </p>
<p class = "text-justify"> In the time remaining until the next match (a day or two), you can perform many other actions to prepare for a new game or for the general development of the team. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "4.2"> <span class = "strong"> 4. 2. Players. </span> You can have several dozen players in your team. You don\'t need to keep too many players in the team, too few is also bad (when players play too often, they get tired, tired play worse). </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify"> <span class = "strong"> 4. 2. 1. Distinctive features of the players. </span> Each player differs from the other by a set of parameters that make him better or worse than others in different situations: </p>
<ul>
<li> <span class = "strong"> Age </span> - from 17 to 35 years old, after the season the player will age by 1 year. Young people, adding a year, become stronger, and veterans aged 31 and older lose strength with each new year and can end their careers. Young people get tired less, veterans are useful as team captains. </li>
<li> <span class = "strong"> Strength </span> is one of the most important parameters: the stronger the player, the better he plays. Strength can be trained in team training centers, strength grows after a successful game and can drop after unsuccessful ones. Your job is to have stronger players and put out a stronger squad to win. </li>
<li> <span class = "strong"> Profile position on the pitch </span> - the position in which the rugby player plays better: defender, forward. Each player can have one or two profile positions. Positions can be trained or changed at the training center. In other positions, the player plays worse than in profile ones. </li>
<li> <span class = "strong"> Special abilities </span> are special skills that give the player additional bonuses in some cases. A player can have no more than four special abilities, but he may not have any. Accessibility is trained in the training center. There are several different special abilities. </li>
<li> <span class = "strong"> Fatigue </span> </li>
<li> <span class = "strong"> Physical form </span> </li>
<li> <span class = "strong"> Nationality </span> </li>
<li> <span class = "strong"> Price </span> </li>
</ul>
<p class = "text-justify"> Each player has a favorite playstyle that may not be familiar to you, but can be learned through the scout center. </p>
<p class = "text-justify"> Favorite playstyle does not change and remains the same throughout a player\'s career. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify"> <span class = "strong"> 4. 2. 2. Selling and buying players - the transfer market. </span> You can buy and sell players on the transfer market. </p>
<p class = "text-justify"> To sell a player, you go to his profile in the "Transfer" section and put him up for auction, which will take place in the next few days. During this time, applications for your player are collected and he is sent to the one who offers more. You can determine the initial bidding price yourself. You can always sell a player to the League for half the price. </p>
<p class = "text-justify"> To buy a player, you are looking for a suitable player on the transfer market, submit a request and wait for bidding on this player. If your application is the largest and you have enough money at the time of the bidding, the player will be transferred to your team. </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p>
<p class = "text-justify" id = "5"> <span class = "strong"> 5. What else to read? </span> You just read our game overview. If you are interested in it, then register, get a command and start playing. </p>
<p class = "text-justify"> You can return to the "Rules of the game" section at any time, for each specific game issue a separate section has been written that describes all the details and nuances. </p>
<p class = "text-justify"> There are hints and explanations on the pages of the site in many places. Experienced managers will help you in the chat and on the forum. </p>
<p class = "text-justify"> If you have any questions about the game, you can report bugs, send ideas and suggestions to the technical support of the site. Have a nice game! </p>
<p class = "text-right text-size-3"> [<a href="#0"> to content </a>] </p> ',
    'title' => 'For beginners',
];
