<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class = "strong text-justify"> Events in the game day generation are carried out in the following order: </p>
<ol>
<li> Closing the site. </li>
<li> Prelaunch preparation. </li>
<li> Generation of auto compositions. </li>
<li> Matches. </li>
<li> Change in fatigue. </li>
<li> Reduction of the lease term and return of the leased ones. </li>
<li> Recalculation of tournament tables. </li>
<li> Recalculation of statistical indicators of players in tournaments. </li>
<li> Player training. </li>
<li> Youth training in sports schools. </li>
<li> Studying players in scout centers. </li>
<li> Reshaping at fitness centers. </li>
<li> Removal of injuries. </li>
<li> Markets: transfer, rental, exchanges. </li>
<li> End of buildings. Those. on this day, players are not yet allowed to change their uniforms while construction is in progress. </li>
<li> Recalculation of ratings of managers and teams. </li>
<li> Opening the site. </li>
</ol> ',
    'title' => 'The order of events when generating a game day',
];
