<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'controllers.logo.index.title' => 'Логотипы команд',
    'controllers.logo.view.bread.index' => 'Логотипы команд',
    'controllers.schedule.index.title' => 'Перевести время',
    'models.forms.sing-in.password.error' => 'Неправильная комбинация логин/пароль',
    'views.analytics.snapshot.date' => 'Дата',
    'views.analytics.snapshot.label.id' => 'Показатель',
    'views.analytics.snapshot.submit' => 'Показать',
    'views.layout.main.label.complaint' => 'Жалобы',
    'views.layout.main.label.generator' => 'Коррекция генератора',
    'views.layout.main.label.log' => 'Логи',
    'views.layout.main.label.logo' => 'Логотипы',
    'views.layout.main.label.logout' => 'Выход',
    'views.layout.main.label.metrics' => 'Показатели сайта',
    'views.layout.main.label.news' => 'Новости',
    'views.layout.main.label.photo' => 'Фотографии',
    'views.layout.main.label.rule' => 'Правил',
    'views.layout.main.label.schedule' => 'Рассписание',
    'views.layout.main.label.snapshot' => 'Слепки сайта',
    'views.layout.main.label.support' => 'Поддержка',
    'views.layout.main.label.team' => 'Команды',
    'views.layout.main.label.team-request' => 'Заявки на команды',
    'views.layout.main.label.turn-off' => 'Выключить',
    'views.layout.main.label.turn-on' => 'Включить',
    'views.layout.main.label.user' => 'Пользватели',
    'views.layout.main.label.version' => 'Версия сайта',
    'views.layout.main.label.vote' => 'Голосования',
    'views.logo.index.th.date' => 'Время заявки',
    'views.logo.index.th.team' => 'Команда',
    'views.photo.index.th.date' => 'Время заявки',
    'views.photo.index.th.user' => 'Пользователь',
    'views.schedule.index.link.future' => 'Вперед в будущее',
    'views.schedule.index.link.past' => 'Назад в прошлое',
    'views.schedule.index.today' => 'Сегодня',
    'views.site.index.amount' => 'Сумма',
    'views.site.index.check' => 'На проверку',
    'views.site.index.link.details' => 'Подробнее',
    'views.site.index.month' => 'Месяц',
    'views.site.index.payment' => 'Платежи',
];
