<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#1.1">1.1. Стоимость игрока.</a>
<br/>
<a href="#1.2">1.2. Зарплата игрока.</a>
<br/>
<a href="#2">2. Как расчитывается зарплата игроков?</a>
<br/>
<a href="#2.1">2.1. Общие сведения - формула расчета.</a>
<br/>
<a href="#2.2">2.2. Зависимость зарплаты от уровня базы.</a>
<br/>
<a href="#2.3">2.3. Зависимость от дивизиона в котором выступает команда.</a>
</p>
<p class="strong text-justify" id="1">1. Общие положения.</p>
<p class="strong text-justify" id="1.1">1.1. Стоимость игрока.</p>
<p class="text-justify">Стоимость игрока - номинальная цена игрока, зависящая от его возраста, силы, наличия спецвозможностей и дополнительной профильной позиции на поле.</p>
<p class="text-justify">Стоимость игрока определяется по формуле: Стоимость игрока = (150 - (28 - В)) ^ 2 * (П - 1 + С + Сп )* 1000, где</p>
<ul>
<li>В - возраст игрока;</li>
<li>П - количество профильных позиций игрока;</li>
<li>C - номинальная сила игрока;</li>
<li>Сп - количество cпецвозможностей игрока (считается путем сложения всех уровней различных спецвозможностей, например игрок Ск3Км2 в сумме имеет 5 спецвозможностей).</li>
</ul>
<p class="text-justify">От стоимости игрока зависит его зарплата и его стартовая цена на трансферном и арендном рынках. Она же учитывается при построении различных рейтингов.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="1.2">1.2. Зарплата игрока.</p>
<p class="text-justify">Зарплата является одной из составляющей расходов команды. Зарплата выплачивается каждому игрока, находящемуся в команде (включая травмированных и взятых в аренду).</p>
<p class="text-justify">Зарплата выплачивается каждый каледарный день.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2">2. Как расчитывается зарплата игроков?</p>
<p class="strong text-justify" id="2.1">2.1. Общие сведения - формула расчета.</p>
<p class="text-justify">Формула расчета зарплаты игроков каждой команды имеет следующий вид: Зарплата игрока за тур = Стоимость игрока * k1 * k2, где</p>
<ul>
<li>k1 - коэффициент зависимости от уровня базы команды;</li>
<li>k2 - коэффициент зависимости от дивизиона, в котором выступает команда.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2.2">2.2. Зависимость зарплаты от уровня базы.</p>
<p class="text-justify">На уровень зарплаты влияет уровень Базы команды. Чем выше этот уровень, тем выше зарплата.
<table class="table table-hover table-bordered">
<tr><th>Уровень базы</th><th>Коэффициент</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0.0003</td></tr>
<tr><td class="text-center">1</td><td class="text-center">0.0004</td></tr>
<tr><td class="text-center">2</td><td class="text-center">0.0005</td></tr>
<tr><td class="text-center">3</td><td class="text-center">0.0006</td></tr>
<tr><td class="text-center">4</td><td class="text-center">0.0007</td></tr>
<tr><td class="text-center">5</td><td class="text-center">0.0008</td></tr>
<tr><td class="text-center">6</td><td class="text-center">0.0009</td></tr>
<tr><td class="text-center">7</td><td class="text-center">0.0010</td></tr>
<tr><td class="text-center">8</td><td class="text-center">0.0011</td></tr>
<tr><td class="text-center">9</td><td class="text-center">0.0012</td></tr>
<tr><td class="text-center">10</td><td class="text-center">0.0013</td></tr>
</table>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2.3">2.3. Зависимость от дивизиона, в котором выступает команда.</p>
<p class="text-justify">В более высоких дивизионах зарплата у игроков выше.</p>
<table class="table table-hover table-bordered">
<tr><th>Дивизион</th><th>Коэффициент</th></tr>
<tr><td class="text-center">D1</td><td class="text-center">1,00</td></tr>
<tr><td class="text-center">D2</td><td class="text-center">0,95</td></tr>
<tr><td class="text-center">D3</td><td class="text-center">0,90</td></tr>
<tr><td class="text-center">D4</td><td class="text-center">0,80</td></tr>
<tr><td class="text-center">Конференция</td><td class="text-center">0,70</td></tr>
</table>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Стоимость и зарплата игроков',
];
