<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Что такое травмы игроков?</a>
<br/>
<a href="#2">2. Виды травм.</a>
</p>
<p class="text-justify" id="1"><span class="strong">1. Что такое травмы игроков?</span> Любой регбист может получить травму по результатам игры. Травмированный игрок не может участвовать в матчах, выделен красным цветом в ростере. Травмы игроков в конце сезона полностью излечиваются.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="2"><span class="strong">2. Виды травм.</span> Травмы условно подразделяются на микро (1-2 дня), легкие (3-4 дня), тяжелые (5-6 дней) и очень тяжелые (7-9 дней).</p>
<p class="text-justify">Все травмы обнаруживаются уже после игры. Виртуальный регбист доигрывает матч до конца без потери силы, однако по возвращении на базу оказывается травмирован и подлежит лечению. Вероятность получения травм целиком и полностью зависит от усталости игрока. Чем она больше, тем вероятнее получение послематчевой травмы.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Травмы игроков',
];
