<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#2">2. Распределение мест в кубке межсезонья.</a>
<br/>
<a href="#3">3. Призовые.</a>
</p>
<p class="text-justify" id="1"><span class="strong">1. Общие положения.</span> Кубок межсезонья - это турнир, который проводится в самом начале каждого сезона. В кубке межсезонья принимают участие все команды Лиги.</p>
<p class="text-justify">Турнир играется в 12 туров по нестабильному календарю, когда для каждой команды выбирается случайный соперник, причем с одной и той же командой можно сыграть только один раз за турнир, а число игр дома и в гостях в конце турнира должно стать равным или отличаться на еденицу (если ваша команда провела нечетное число матчей)..</p>
<p class="text-justify">В матчах турнира есть домашний бонус - в родных стенах команды играют сильнее.</p>
<p class="text-justify">Каждая команда имеет право сыграть 2 матча на супере и 2 матча на отдыхе во время розыгрыша кубка межсезонья.</p>
<p class="text-justify">Игры кубка межсезонья - это игры типа B ("обязательные"), т. е. в них изменяется усталость игроков. Подробнее о разных видах игр можно почитать в разделе про Усталость игроков (У).</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="2"><span class="strong">2. Распределение мест в кубке межсезонья.</span> В итоговом распределении мест в порядке приоритетности учитываются следующие параметры:</p>
<ul>
<li>набранные турнирные очки (чем больше, тем выше);</li>
<li>победы (чем больше, тем выше);</li>
<li>ничьи (чем больше, тем выше);</li>
<li>разница игровых очков (чем больше, тем выше);</li>
<li>набраных игровых очков (чем больше, тем выше);</li>
<li>по рейтингу Vs (чем меньше, тем выше);</li>
</ul>
<p class="text-justify">При равенстве всех вышеназванных показателей проводится жребий.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3"><span class="strong">3. Призовые.</span> За участие в Кубке межсезонья команды получают призовые, которые рассчитывается по формуле:</p>
<p class="text-justify">2000000 * 0.98 ^ (место в турнирной таблице - 1)</p>
<p class="text-justify">Итоговые места команд по результатам кубка межсезонья учитываются только при распределении призового фонда турнира. Создание новых дивизионов и стран проводится по результатам участия команд в конференции любительских клубов (а не кубка межсезонья).</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Кубок межсезонья',
];
