<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#2">2. Дивизионы.</a>
<br/>
<a href="#3">3. Расписание игр.</a>
<br/>
<a href="#4">4. Ротация между дивизионами.</a>
<br/>
<a href="#5">5. Изменение усталости игроков.</a>
<br/>
<a href="#6">6. Распределение мест в турнирной таблице.</a>
<br/>
<a href="#7">7. Призовые.</a>
</p>
<p class="text-justify" id="1"><span class="strong">1. Регламент.</span> Чемпионаты стран являются основным турниром для каждой команды в Лиге. Команды участвуют в чемпионатах своих стран, чемпионат проводится один раз в сезон. Чемпионаты проводятся по странам.</p>
<p class="text-justify">Победители высшего дивизиона чемпионата (D1) помимо звания чемпиона страны получают право представлять страну в лиге чемпионов.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="2"><span class="strong">2. Дивизионы.</span> Одной стране может соответствовать два или более дивизионов, в каждом из которых 16 команд. Каждый дивизион, по сути, представляет собой отдельный турнир с той лишь разницей, что между дивизионами одной страны существует ротация команд.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3"><span class="strong">3. Расписание игр.</span> Все чемпионаты играются по двухкруговой системе, при этом каждая команда играет со всеми остальными по два матча - дома и на выезде (всего 30 матчей).</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="4"><span class="strong">4. Ротация между дивизионами.</span> По завершению чемпионата 2 лучшие команды меняются местами с двумя худшими командами более высокого дивизиона.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="5"><span class="strong">5. Изменение усталости игроков.</span> В зависимости от усталости игрока меняется и то, как он будет проявлять себя в очередном матче вашей команды. Чем больше матчей подряд сыграет ваш игрок, тем более уставшим он будет выходить на поле. Усталость в начале чемпионата у всех игроков выводится на уровень медцентра тех команд, в которых они находились перед стартом этого соревнования (готовились). Будьте внимательны: если в момент выведение усталости на уровень медцентра строится медцентр или база - все ваши игроки начнут участие в соревновании с усталостью медцентра нулевого уровня. Подробнее Усталость игроков (У).</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="6"><span class="strong">6. Распределение мест в турнирной таблице.</span> В итоговом распределении мест в порядке приоритетности учитываются следующие параметры:</p>
<ul>
<li>набранные турнирные очки (чем больше, тем выше);</li>
<li>победы (чем больше, тем выше);</li>
<li>ничьи (чем больше, тем выше);</li>
<li>разница игровых очков (чем больше, тем выше);</li>
<li>набраных игровых очков (чем больше, тем выше);</li>
<li>по рейтингу Vs (чем меньше, тем выше);</li>
</ul>
<p class="text-justify">При равенстве всех вышеназванных показателей проводится жребий.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="7"><span class="strong">7. Призовые.</span> По результатам чемпионата команды получают призовые в зависимости от дивизиона.</p>
<p class="text-justify">Призовые для чемпионата рассчитываются по формуле:</p>
<p class="text-justify">20000000 * 0.98 ^ (( М - 1 ) + ( Д - 1 ) * 16), где</p>
<ul>
<li>М - место в турнирной таблице;</li>
<li>Д - уровень дивизиона;</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Чемпионаты стран',
];
