<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify">События в генерации игрового дня проводятся в следующей очерёдности:</p>
<ol>
<li>Закрытие сайта.</li>
<li>Предстартовая подготовка.</li>
<li>Генерация автосоставов.</li>
<li>Матчи.</li>
<li>Изменение усталости.</li>
<li>Уменьшение срока аренды и возврат арендованных.</li>
<li>Пересчёт турнирных таблиц турниров.</li>
<li>Пересчёт статистических показателей игроков в турнирах.</li>
<li>Тренировки игроков.</li>
<li>Подготовка молодёжи в спортшколах.</li>
<li>Изучение игроков в скаут-центрах.</li>
<li>Изменение формы в центрах физ.подготовки.</li>
<li>Снятие травм.</li>
<li>Рынки: трансферный, арендный, обмены.</li>
<li>Окончание построек. Т.е. в этот день еще нельзя менять форму игрокам, если идёт стройка.</li>
<li>Пересчет рейтингов менеджеров и команд.</li>
<li>Открытие сайта.</li>
</ol>',
    'title' => 'Очерёдность событий при генерации игрового дня',
];
