<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'text' => '<p class="strong text-justify" id="0">Содержание</p>
<p class="text-justify">
<a href="#1">1. Общие положения.</a>
<br/>
<a href="#1.1">1.1. Что такое база команды?</a>
<br/>
<a href="#1.2">1.2. Строительство баз.</a>
<br/>
<a href="#1.3">1.3. Строительство спортивных сооружений.</a>
<br/>
<a href="#1.4">1.4. Дополнительные правила строительства.</a>
<br/>
<a href="#1.5">1.5. Оплата за содержание.</a>
<br/>
<a href="#2">2. База команды.</a>
<br/>
<a href="#2.1">2.1. Что такое база команды?</a>
<br/>
<a href="#2.2">2.2. Таблица уровней баз команд.</a>
<br/>
<a href="#3">3. Спортшкола.</a>
<br/>
<a href="#3.1">3.1. Что такое спортшкола?</a>
<br/>
<a href="#3.2">3.2. Как готовить молодежь в спортшколе?</a>
<br/>
<a href="#3.3">3.3. Форма и усталость молодежи из спортшкол.</a>
<br/>
<a href="#3.4">3.4. Таблица уровней спортшкол.</a>
<br/>
<a href="#4">4. Тренировочный центр.</a>
<br/>
<a href="#4.1">4.1. Что такое тренировочный центр?</a>
<br/>
<a href="#4.2">4.2. Таблица уровней тренировочных центров.</a>
<br/>
<a href="#4.3">4.3. Ограничения по тренировке.</a>
<br/>
<a href="#4.4">4.4. Снятие игроков с тренировки.</a>
<br/>
<a href="#5">5. Медицинский центр.</a>
<br/>
<a href="#5.1">5.1. Что такое медицинский центр?</a>
<br/>
<a href="#5.2">5.2. Таблица уровней медицинских центров.</a>
<br/>
<a href="#6">6. Центр физподготовки.</a>
<br/>
<a href="#6.1">6.1. Что такое центр физподготовки?</a>
<br/>
<a href="#6.2">6.2. Таблица уровней центров физподготовки.</a>
<br/>
<a href="#7">7. Скаут-центры.</a>
<br/>
<a href="#7.1">7.1. Что такое скаут-центр?</a>
<br/>
<a href="#7.2">7.2. Скрытые параметры игрока.</a>
<br/>
<a href="#7.3">7.3. Изучение усталости, автосоставов и ИП/ОП игроков соперников.</a>
<br/>
<a href="#7.4">7.4. Таблица уровней скаут-центров.</a>
<br/>
<a href="#7.5">7.5. Секреты работы скаут-центров.</a>
</p>
<p class="strong text-justify" id="1">1. Общие положения.</p>
<p class="text-justify" id="1.1"><span class="strong">1.1. Что такое база команды?</span> Каждая команда может построить и расширять свою командную базу. База - это строительная площадка для различных спортивных сооружений, которые дают различные преимущества команде, в частности, лучшую восстанавливаемость после травм, подготовку молодых игроков, тренировку силы, спецвозможностей, профильных позиций на поле и т.д. Всего разрешена постройка пяти разных видов сооружений - спортшкола, тренировочный центр, медицинский центр, центр физподготовки, скаут-центр.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="1.2"><span class="strong">1.2. Строительство баз.</span> Команда может в любое время начать расширение базы, если есть достаточно денег для оплаты строительства.</p>
<p class="text-justify">Во время строительства базы команда не может пользоваться всеми своими строениями (считается, что спортивные сооружения в данный момент у команды нулевого уровня).</p>
<p class="text-justify">Во время строительства любого другого строения, оно не функционирует, т.е. считается, что у команды в данный момент это строение нулевого уровня.</p>
<p class="text-justify">Например, если в день выведения усталости на уровень баз вы все еще строите медцентр или всю базу, то усталость игроков вашей команды будет выведена на 50%. Однако совершенно безболезненно в это время можно строить тренировочный центр - на работу медцентра это никак не повлияет.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="1.3"><span class="strong">1.3. Строительство спортивных сооружений.</span> Команда может в любое время  начать строительство или улучшение имеющихся строений, если есть достаточно денег для оплаты строительства, есть свободный слот на базе и уровень базы соответствует минимальным требованиям для данного сооружения. Во время улучшения спортивного сооружения команда не может им пользоваться.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="1.4">1.4. Дополнительные правила строительства.</p>
<p class="text-justify">Базы и спортивные сооружения строятся уровень за уровнем (например, нельзя сразу построить медцентр 10 уровня, нужно пройти весь путь строительства от 1).</p>
<p class="text-justify">Проводить строительство единовременно можно только одной постройки (либо расширять базу), следующее строительство только, когда закончено или отменено предыдущее.</p>
<p class="text-justify">Прекратить строительство можно в любой момент, команде вернется 100% стоимости начатого строительства.</p>
<p class="text-justify">Продать постройку нельзя, если на базе команды идёт строительство других сооружений (или идёт расширение базы).</p>
<p class="text-justify">Единица времени для строительства, тренировок и т.д. - один календарный день.</p>
<p class="text-justify">В последний день сезона все стройки успешно заканчиваются. Таким образом в конце сезона можно начать какое-нибудь длительное строительство и оно быстро закончится. Таким ускоренным образом можно построить только одно сооружение в сезон.</p>
<p class="text-justify">Разрушать строения на базе команды нельзя в первые 7 дней после получения команды.</p>
<p class="text-justify">Разрушать строения на базе команды нельзя, если команда за последние 7 дней более 25% матчей играла автосоставами.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="1.5"><span class="strong">1.5. Оплата за содержание.</span> В начале каждого сезона с команды удерживается стоимость содержания базы и всех занятых слотов на ней. Свободные слоты не оплачиваются. При постройке баз и сооружений оплата за содержание не снимается.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="2">2. База команды.</p>
<p class="text-justify" id="2.1"><span class="strong">2.1. Что такое база команды?</span> База - это основа для дальнейшего строительства на ней спортивных сооружений. Есть 10 уровней баз. Каждый уровень предполагает большее число слотов для строительства, позволяет обеспечить минимальные требования для сооружений более высокого качества, но и соответственно имеет большую стоимость постройки и содержания.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="2.2"><span class="strong">2.2. Таблица уровней баз команд.</span> Стоимость и параметры баз команд вы можете узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Уровень</th><th>Слотов (не менее)</th><th>Слотов (не более)</th><th>Cодержание базы</th><th>Cодержание слота</th><th>Цена продажи</th><th>Скорость постройки</th><th>Цена постройки</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-right">0$</td><td class="text-right">0$</td><td class="text-right">0$</td><td class="text-center">0</td><td class="text-right">0$</td></tr>
<tr><td class="text-center">1</td><td class="text-center">0</td><td class="text-center">5</td><td class="text-right">50 000$</td><td class="text-right">25 000$</td><td class="text-right">375 000$</td><td class="text-center">2</td><td class="text-right">500 000$</td></tr>
<tr><td class="text-center">2</td><td class="text-center">3</td><td class="text-center">10</td><td class="text-right">100 000$</td><td class="text-right">50 000$</td><td class="text-right">750 000$</td><td class="text-center">4</td><td class="text-right">1 000 000$</td></tr>
<tr><td class="text-center">3</td><td class="text-center">8</td><td class="text-center">15</td><td class="text-right">150 000$</td><td class="text-right">75 000$</td><td class="text-right">1 500 000$</td><td class="text-center">6</td><td class="text-right">2 000 000$</td></tr>
<tr><td class="text-center">4</td><td class="text-center">13</td><td class="text-center">20</td><td class="text-right">200 000$</td><td class="text-right">100 000$</td><td class="text-right">2 225 000$</td><td class="text-center">8</td><td class="text-right">3 000 000$</td></tr>
<tr><td class="text-center">5</td><td class="text-center">18</td><td class="text-center">25</td><td class="text-right">250 000$</td><td class="text-right">125 000$</td><td class="text-right">3 000 000$</td><td class="text-center">10</td><td class="text-right">4 000 000$</td></tr>
<tr><td class="text-center">6</td><td class="text-center">23</td><td class="text-center">30</td><td class="text-right">300 000$</td><td class="text-right">150 000$</td><td class="text-right">3 750 000$</td><td class="text-center">12</td><td class="text-right">5 000 000$</td></tr>
<tr><td class="text-center">7</td><td class="text-center">28</td><td class="text-center">35</td><td class="text-right">350 000$</td><td class="text-right">175 000$</td><td class="text-right">4 500 000$</td><td class="text-center">14</td><td class="text-right">6 000 000$</td></tr>
<tr><td class="text-center">8</td><td class="text-center">33</td><td class="text-center">40</td><td class="text-right">400 000$</td><td class="text-right">200 000$</td><td class="text-right">5 250 000$</td><td class="text-center">16</td><td class="text-right">7 000 000$</td></tr>
<tr><td class="text-center">9</td><td class="text-center">38</td><td class="text-center">45</td><td class="text-right">450 000$</td><td class="text-right">225 000$</td><td class="text-right">6 000 000$</td><td class="text-center">18</td><td class="text-right">8 000 000$</td></tr>
<tr><td class="text-center">10</td><td class="text-center">43</td><td class="text-center">50</td><td class="text-right">500 000$</td><td class="text-right">250 000$</td><td class="text-right">7 500 000$</td><td class="text-center">20</td><td class="text-right">10 000 000$</td></tr>
</table>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="3">3. Спортшкола.</p>
<p class="text-justify" id="3.1"><span class="strong">3.1. Что такое спортшкола?</span> Спортшкола - это строение на базе команды, позволяющее приводить в вашу команду новых молодых игроков. Чем выше уровень спортшколы, тем лучше подготовленные молодые игроки и больше их количество.</p>
<p class="text-justify">Молодые игроки приходят в вашу команду бесплатно.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3.2"><span class="strong">3.2. Как готовить молодежь в спортшколе?</span> Для того, чтобы начать подготовку молодого игрока в спортшколе, вам нужно указать игроку:
<ul>
<li>позицию на поле;</li>
<li>спецвозможность;</li>
<li>любимый стиль игры.</li>
</ul>
<p class="text-justify">Подготовка нового игрока длится несколько дней в зависимости от уровня спортшколы.</p>
<p class="text-justify">Можно подготовить двух новых игроков за один сезон, но делать это нужно поочерёдно - сначала подготовить первого игрока, потом второго.</p>
<p class="text-justify">После каждого игрового дня прогресс начатой подготовки молодого игрока к переходу в команду увеличивается.</p>
<p class="text-justify">Как только прогресс достигает 100% - подготовка успешно завершается, и ваш молодой игрок появляется в команде. В последний день сезона любая начавшаяся подготовка молодого игрока всегда успешно завершается, даже если это происходит досрочно.</p>
<p class="text-justify">Нельзя строить или разрушать спортшколу или базу команды, если спортшкола находится в процессе подготовки нового молодого игрока. Нельзя начинать подготовку молодого игрока, если спортшкола или база команды находятся в процессе строительства.</p>
<p class="text-justify">Отменить подготовку молодого игрока к переходу в команду можно в любой момент, но прогресс подготовки будет потерян.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3.3"><span class="strong">3.3. Форма и усталость молодежи из спортшкол.</span> Молодые игроки приходят из спортшкол в свои команды со случайной формой и с усталостью на уровне командного медцентра (если медцентр на момент появления молодых игроков не работает, его уровень равен нулю). У молодых игроков в момент перехода в команду из спортшколы ИП=0, ОП=1.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="3.4"><span class="strong">3.4. Таблица уровней спортшкол.</span> Сегодняшнюю стоимость и параметры спортшкол вы можете узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Уровень</th><th>Мин уровень базы</th><th>Скорость подготовки игрока</th><th>Игроков</th><th>Из них со стилем</th><th>Из них со спецвозможностью</th><th>Сила игрока</th><th>Цена продажи</th><th>Скорость постройки</th><th>Цена постройки</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-right">0$</td><td class="text-center">0</td><td class="text-right">0$</td></tr>
<tr><td class="text-center">1</td><td class="text-center">1</td><td class="text-center">1</td><td class="text-center">2</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">34</td><td class="text-right">187 500$</td><td class="text-center">1</td><td class="text-right">250 000$</td></tr>
<tr><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">2</td><td class="text-center">2</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">36</td><td class="text-right">375 000$</td><td class="text-center">2</td><td class="text-right">500 000$</td></tr>
<tr><td class="text-center">3</td><td class="text-center">2</td><td class="text-center">3</td><td class="text-center">2</td><td class="text-center">0</td><td class="text-center">1</td><td class="text-center">38</td><td class="text-right">562 500$</td><td class="text-center">3</td><td class="text-right">750 000$</td></tr>
<tr><td class="text-center">4</td><td class="text-center">2</td><td class="text-center">4</td><td class="text-center">2</td><td class="text-center">0</td><td class="text-center">1</td><td class="text-center">40</td><td class="text-right">750 000$</td><td class="text-center">4</td><td class="text-right">1 000 000$</td></tr>
<tr><td class="text-center">5</td><td class="text-center">3</td><td class="text-center">5</td><td class="text-center">2</td><td class="text-center">0</td><td class="text-center">2</td><td class="text-center">42</td><td class="text-right">937 500$</td><td class="text-center">5</td><td class="text-right">1 250 000$</td></tr>
<tr><td class="text-center">6</td><td class="text-center">3</td><td class="text-center">6</td><td class="text-center">2</td><td class="text-center">0</td><td class="text-center">2</td><td class="text-center">44</td><td class="text-right">1 125 000$</td><td class="text-center">6</td><td class="text-right">1 500 000$</td></tr>
<tr><td class="text-center">7</td><td class="text-center">4</td><td class="text-center">7</td><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">2</td><td class="text-center">46</td><td class="text-right">1 312 500$</td><td class="text-center">7</td><td class="text-right">1 750 000$</td></tr>
<tr><td class="text-center">8</td><td class="text-center">4</td><td class="text-center">8</td><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">2</td><td class="text-center">48</td><td class="text-right">1 500 000$</td><td class="text-center">8</td><td class="text-right">2 000 000$</td></tr>
<tr><td class="text-center">9</td><td class="text-center">5</td><td class="text-center">9</td><td class="text-center">2</td><td class="text-center">2</td><td class="text-center">2</td><td class="text-center">50</td><td class="text-right">1 687 500$</td><td class="text-center">9</td><td class="text-right">2 250 000$</td></tr>
<tr><td class="text-center">10</td><td class="text-center">5</td><td class="text-center">10</td><td class="text-center">2</td><td class="text-center">2</td><td class="text-center">2</td><td class="text-center">52</td><td class="text-right">1 875 000$</td><td class="text-center">10</td><td class="text-right">2 500 000$</td></tr>
</table>
<p class="text-justify">Если к вам приходит игрок выбранного вами стиля, то в команду он приходит полностью изученным только при условии наличия скаут-центра пятого уровня и выше. При отсутствии скаут-центра нужного уровня вы будете знать, что игрок скоросного стиля, но игрок будет числиться неизученным и для полноценного использования известных вам данных вам придётся изучать его в скаут-центре.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="4">4. Тренировочный центр.</p>
<p class="text-justify" id="4.1"><span class="strong">4. 1. Что такое тренировочный центр?</span> Тренировочный центр - это спортивное сооружение, позволяющее тренировать вашим регбистам дополнительные баллы силы, а так же новые спецвозможности и профильные позиции на поле. Каждая тренировка имеет свою стоимость. Уровень тренировочного центра позволяет увеличивать максимальное число тренировок в вашей команде за сезон и увеличивать скорость тренировки. Увеличение уровня тренировочного центра в течение сезона увеличивает максимальное число тренировок за сезон, но не сбрасывает этот счетчик. Чтобы начать постройку тренировочного центра, нужно снять с тренировок всех игроков.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="4.2"><span class="strong">4.2. Таблица уровней тренировочных центров.</span> Параметры тренировочных центров вы можете узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Уровень</th><th>Мин уровень базы</th><th>Скорость тренировки</th><th>Баллов силы</th><th>Стоимость</th><th>Спецвозможности</th><th>Стоимость</th><th>Позиции</th><th>Стоимость</th><th>Цена продажи</th><th>Скорость постройки</th><th>Цена постройки</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0%</td><td class="text-center">0</td><td class="text-right">0$</td><td class="text-center">0</td><td class="text-center">0$</td><td class="text-center">0</td><td class="text-center">0$</td><td class="text-right">0$</td><td class="text-center">0</td><td class="text-right">0$</td></tr>
<tr><td class="text-center">1</td><td class="text-center">1</td><td class="text-center">5%-15%</td><td class="text-center">5</td><td class="text-right">25 000$</td><td class="text-center">1</td><td class="text-center">50 000$</td><td class="text-center">1</td><td class="text-center">50 000$</td><td class="text-right">187 500$</td><td class="text-center">1</td><td class="text-right">250 000$</td></tr>
<tr><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">15%-25%</td><td class="text-center">10</td><td class="text-right">50 000$</td><td class="text-center">1</td><td class="text-center">100 000$</td><td class="text-center">1</td><td class="text-center">100 000$</td><td class="text-right">375 000$</td><td class="text-center">2</td><td class="text-right">500 000$</td></tr>
<tr><td class="text-center">3</td><td class="text-center">2</td><td class="text-center">25%-35%</td><td class="text-center">15</td><td class="text-right">75 000$</td><td class="text-center">2</td><td class="text-center">150 000$</td><td class="text-center">2</td><td class="text-center">150 000$</td><td class="text-right">562 500$</td><td class="text-center">3</td><td class="text-right">750 000$</td></tr>
<tr><td class="text-center">4</td><td class="text-center">2</td><td class="text-center">35%-45%</td><td class="text-center">20</td><td class="text-right">100 000$</td><td class="text-center">2</td><td class="text-center">200 000$</td><td class="text-center">2</td><td class="text-center">200 000$</td><td class="text-right">750 000$</td><td class="text-center">4</td><td class="text-right">1 000 000$</td></tr>
<tr><td class="text-center">5</td><td class="text-center">3</td><td class="text-center">45%-55%</td><td class="text-center">25</td><td class="text-right">125 000$</td><td class="text-center">3</td><td class="text-center">250 000$</td><td class="text-center">3</td><td class="text-center">250 000$</td><td class="text-right">937 500$</td><td class="text-center">5</td><td class="text-right">1 250 000$</td></tr>
<tr><td class="text-center">6</td><td class="text-center">3</td><td class="text-center">55%-65%</td><td class="text-center">30</td><td class="text-right">150 000$</td><td class="text-center">3</td><td class="text-center">300 000$</td><td class="text-center">3</td><td class="text-center">300 000$</td><td class="text-right">1 125 000$</td><td class="text-center">6</td><td class="text-right">1 500 000$</td></tr>
<tr><td class="text-center">7</td><td class="text-center">4</td><td class="text-center">65%-75%</td><td class="text-center">35</td><td class="text-right">175 000$</td><td class="text-center">4</td><td class="text-center">350 000$</td><td class="text-center">4</td><td class="text-center">350 000$</td><td class="text-right">1 312 500$</td><td class="text-center">7</td><td class="text-right">1 750 000$</td></tr>
<tr><td class="text-center">8</td><td class="text-center">4</td><td class="text-center">75%-85%</td><td class="text-center">40</td><td class="text-right">200 000$</td><td class="text-center">4</td><td class="text-center">400 000$</td><td class="text-center">4</td><td class="text-center">400 000$</td><td class="text-right">1 500 000$</td><td class="text-center">8</td><td class="text-right">2 000 000$</td></tr>
<tr><td class="text-center">9</td><td class="text-center">5</td><td class="text-center">85%-95%</td><td class="text-center">45</td><td class="text-right">225 000$</td><td class="text-center">5</td><td class="text-center">450 000$</td><td class="text-center">5</td><td class="text-center">450 000$</td><td class="text-right">1 687 500$</td><td class="text-center">9</td><td class="text-right">2 250 000$</td></tr>
<tr><td class="text-center">10</td><td class="text-center">5</td><td class="text-center">100%</td><td class="text-center">50</td><td class="text-right">250 000$</td><td class="text-center">5</td><td class="text-center">500 000$</td><td class="text-center">5</td><td class="text-center">500 000$</td><td class="text-right">1 875 000$</td><td class="text-center">10</td><td class="text-right">2 500 000$</td></tr>
</table>
<p class="text-justify">Игрок, находящийся на тренировке, не может участвовать в сделках.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="4.3"><span class="strong">4.3. Ограничения по тренировке.</span> Не могут тренироваться игроки, которые начинают стареть (с 35 лет).</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="4.4"><span class="strong">4.4. Снятие игроков с тренировки.</span> Назначенные тренировки можно в любой момент остановить. Балл силы, спецвозможность или профильная позиция в этом случае не потеряется, а деньги, потраченные на оплату тренировки, вернутся в кассу команды.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="5">5. Медицинский центр.</p>
<p class="text-justify" id="5.1"><span class="strong">5.1. Что такое медицинский центр?</span> Медицинский центр отвечает за базовую усталость, с которой регбисты команды подходят к началу соревнований и приходят из спортшколы, а так же за усталость после восстановления от травм:</p>
<ul>
<li>усталость выводится на базовый уровень перед началом крупных турниров;</li>
<li>игроки из спортшкол приходят в команду с базовой усталостью;</li>
<li>игрок, восстановившийся после травмы, имеет базовую усталость, которую обеспечивает после восстановления от травм медицинский центр, имеющийся в команде.</li>
</ul>
<p class="text-justify">Чем выше уровень медцентра, тем меньше базовая усталость регбистов.</p>
<p class="text-justify">Если медицинский центр находится в режиме строительства нового уровня или строится новый уровень базы команды, то медицинский центр работать не может, и игроки в это время при необходимости вывода усталости на базовый уровень получают 50% усталости.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="5.2"><span class="strong">5.2. Таблица уровней медицинских центров.</span> Стоимость и параметры медицинских центров вы можете узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Уровень</th><th>Мин уровень базы</th><th>Базовый уровень усталости</th><th>Цена продажи</th><th>Скорость постройки</th><th>Цена постройки</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">50%</td><td class="text-right">0$</td><td class="text-center">0</td><td class="text-right">0$</td></tr>
<tr><td class="text-center">1</td><td class="text-center">1</td><td class="text-center">45%</td><td class="text-right">187 500$</td><td class="text-center">1</td><td class="text-right">250 000$</td></tr>
<tr><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">40%</td><td class="text-right">375 000$</td><td class="text-center">2</td><td class="text-right">500 000$</td></tr>
<tr><td class="text-center">3</td><td class="text-center">2</td><td class="text-center">35%</td><td class="text-right">562 500$</td><td class="text-center">3</td><td class="text-right">750 000$</td></tr>
<tr><td class="text-center">4</td><td class="text-center">2</td><td class="text-center">30%</td><td class="text-right">750 000$</td><td class="text-center">4</td><td class="text-right">1 000 000$</td></tr>
<tr><td class="text-center">5</td><td class="text-center">3</td><td class="text-center">25%</td><td class="text-right">937 500$</td><td class="text-center">5</td><td class="text-right">1 250 000$</td></tr>
<tr><td class="text-center">6</td><td class="text-center">3</td><td class="text-center">20%</td><td class="text-right">1 125 000$</td><td class="text-center">6</td><td class="text-right">1 500 000$</td></tr>
<tr><td class="text-center">7</td><td class="text-center">4</td><td class="text-center">15%</td><td class="text-right">1 312 500$</td><td class="text-center">7</td><td class="text-right">1 750 000$</td></tr>
<tr><td class="text-center">8</td><td class="text-center">4</td><td class="text-center">10%</td><td class="text-right">1 500 000$</td><td class="text-center">8</td><td class="text-right">2 000 000$</td></tr>
<tr><td class="text-center">9</td><td class="text-center">5</td><td class="text-center">5%</td><td class="text-right">1 687 500$</td><td class="text-center">9</td><td class="text-right">2 250 000$</td></tr>
<tr><td class="text-center">10</td><td class="text-center">5</td><td class="text-center">0%</td><td class="text-right">1 875 000$</td><td class="text-center">10</td><td class="text-right">2 500 000$</td></tr>
</table>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="6">6. Центр физподготовки.</p>
<p class="text-justify" id="6.1"><span class="strong">6.1. Что такое центр физподготовки?</span> Центр физподготовки - это место работы физиотерапевтов, тренеров, занимающихся физической формой игроков и команды в целом. Их и ваша задача - распланировать подготовку команды так, чтобы к самым ответственным матчам команда была в оптимальной физической форме. С увеличением уровня центра физподготовки увеличивается и максимальное число изменений физической формы игрокам. Центр физподготовки позволяет получить и доп. преимущества в восстанавливаемости игроков в дни отдыха от матчей.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="6.2"><span class="strong">6.2. Таблица уровней центров физподготовки.</span> Стоимость и параметры центров физподготовки вы можете узнать из таблицы:</p>
<table class="table table-bordered table-hover">
<tr><th>Уровень</th><th>Мин уровень базы</th><th>Число изменений физ.формы</th><th>Бонус к уменьшению усталости игроков</th><th>Цена продажи</th><th>Скорость постройки</th><th>Цена постройки</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">+2%</td><td class="text-right">0$</td><td class="text-center">0</td><td class="text-right">0$</td></tr>
<tr><td class="text-center">1</td><td class="text-center">1</td><td class="text-center">5</td><td class="text-center">+1%</td><td class="text-right">187 500$</td><td class="text-center">1</td><td class="text-right">250 000$</td></tr>
<tr><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">10</td><td class="text-center">+1%</td><td class="text-right">375 000$</td><td class="text-center">2</td><td class="text-right">500 000$</td></tr>
<tr><td class="text-center">3</td><td class="text-center">2</td><td class="text-center">15</td><td class="text-center">0%</td><td class="text-right">562 500$</td><td class="text-center">3</td><td class="text-right">750 000$</td></tr>
<tr><td class="text-center">4</td><td class="text-center">2</td><td class="text-center">20</td><td class="text-center">0%</td><td class="text-right">750 000$</td><td class="text-center">4</td><td class="text-right">1 000 000$</td></tr>
<tr><td class="text-center">5</td><td class="text-center">3</td><td class="text-center">25</td><td class="text-center">-1%</td><td class="text-right">937 500$</td><td class="text-center">5</td><td class="text-right">1 250 000$</td></tr>
<tr><td class="text-center">6</td><td class="text-center">3</td><td class="text-center">30</td><td class="text-center">-1%</td><td class="text-right">1 125 000$</td><td class="text-center">6</td><td class="text-right">1 500 000$</td></tr>
<tr><td class="text-center">7</td><td class="text-center">4</td><td class="text-center">35</td><td class="text-center">-2%</td><td class="text-right">1 312 500$</td><td class="text-center">7</td><td class="text-right">1 750 000$</td></tr>
<tr><td class="text-center">8</td><td class="text-center">4</td><td class="text-center">40</td><td class="text-center">-2%</td><td class="text-right">1 500 000$</td><td class="text-center">8</td><td class="text-right">2 000 000$</td></tr>
<tr><td class="text-center">9</td><td class="text-center">5</td><td class="text-center">45</td><td class="text-center">-3%</td><td class="text-right">1 687 500$</td><td class="text-center">9</td><td class="text-right">2 250 000$</td></tr>
<tr><td class="text-center">10</td><td class="text-center">5</td><td class="text-center">50</td><td class="text-center">-3%</td><td class="text-right">1 875 000$</td><td class="text-center">10</td><td class="text-right">2 500 000$</td></tr>
</table>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="7">7. Скаут-центры.</p>
<p class="text-justify" id="7.1"><span class="strong">7.1. Что такое скаут-центр?</span> Скаут-центр - место работы скаутов, занимающихся изучением:</p>
<ul>
<li>скрытых параметров игроков команды;</li>
<li>усталости и ИП/ОП игроков соперников;</li>
<li>физической формы игроков соперников;</li>
<li>игроков на трансфере при совершении сделок.</li>
</ul>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="7.2"><span class="strong">7.2. Скрытые параметры игрока.</span> В игре у регбистов есть скрытый параметры - любимый стиль игры, который дается им природой при рождении и не меняется на протяжении их карьеры. Этот параметр неизвестен широкой общественности. Для того, чтобы любимый стиль игрока стал известен вам - его нужно изучить в скаут-центре.</p>
<p class="text-justify">Изучение стиля игрока в скаут-центре происходит в несколько этапов. Каждое изучение любимого стиля игры регбиста отбрасывает из списка один неправильный стиль. Таким образом, только потратив 3 изучения стиля на одного игрока менеджер команды может узнать тот самый единственный любимый стиль регбиста, при игре которым он играет сильнее.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="7.3">7.3. Изучение усталости, автосоставов и ИП/ОП игроков соперников.</p>
<p class="text-justify">Отправили ли тренеры команд-соперников составы на ближайшие игры с вашей командой могут увидеть на странице отправки состава владельцы команд со скаут-центрами восьмого и выше уровня. Эта информация является лишь незначительным дополнительным бонусом скаут-центра, т.к. состав соперника может быть отправлен за секунду до начала генерации.</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="text-justify" id="7.4"><span class="strong">7.4. Таблица уровней скаут-центров.</span> Стоимость и параметры скаут-центров вы можете узнать из двух таблиц.</p>
<p class="text-justify">Изучение чужих игроков:</p>
<table class="table table-bordered table-hover">
<tr><th>Уровень</th><th>Мин уровень базы</th><th>Соперник (ИП/ОП)</th><th>Соперник (У)</th><th>Соперник (Ф)</th><th>Рынки (ИП/ОП)</th><th>Рынки (У)</th><th>Рынки (Ф)</th><th>Цена продажи</th><th>Скорость постройки</th><th>Цена постройки</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-right">0$</td><td class="text-center">0</td><td class="text-right">0$</td></tr>
<tr><td class="text-center">1</td><td class="text-center">1</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">+</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-right">187 500$</td><td class="text-center">1</td><td class="text-right">250 000$</td></tr>
<tr><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">-</td><td class="text-right">375 000$</td><td class="text-center">2</td><td class="text-right">500 000$</td></tr>
<tr><td class="text-center">3</td><td class="text-center">2</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">562 500$</td><td class="text-center">3</td><td class="text-right">750 000$</td></tr>
<tr><td class="text-center">4</td><td class="text-center">2</td><td class="text-center">+</td><td class="text-center">-</td><td class="text-center">-</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">750 000$</td><td class="text-center">4</td><td class="text-right">1 000 000$</td></tr>
<tr><td class="text-center">5</td><td class="text-center">3</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">-</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">937 500$</td><td class="text-center">5</td><td class="text-right">1 250 000$</td></tr>
<tr><td class="text-center">6</td><td class="text-center">3</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">1 125 000$</td><td class="text-center">6</td><td class="text-right">1 500 000$</td></tr>
<tr><td class="text-center">7</td><td class="text-center">4</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">1 312 500$</td><td class="text-center">7</td><td class="text-right">1 750 000$</td></tr>
<tr><td class="text-center">8</td><td class="text-center">4</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">1 500 000$</td><td class="text-center">8</td><td class="text-right">2 000 000$</td></tr>
<tr><td class="text-center">9</td><td class="text-center">5</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">1 687 500$</td><td class="text-center">9</td><td class="text-right">2 250 000$</td></tr>
<tr><td class="text-center">10</td><td class="text-center">5</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-center">+</td><td class="text-right">1 875 000$</td><td class="text-center">10</td><td class="text-right">2 500 000$</td></tr>
</table>
<p class="text-justify">Изучение своих игроков:</p>
<table class="table table-bordered table-hover">
<tr><th>Уровень</th><th>Мин уровень базы</th><th>Скорость изучения</th><th>Любимый стиль</th><th>Стоимость изучения</th></tr>
<tr><td class="text-center">0</td><td class="text-center">0</td><td class="text-center">0%</td><td class="text-center">0</td><td class="text-right">0$</td></tr>
<tr><td class="text-center">1</td><td class="text-center">1</td><td class="text-center">5%-15%</td><td class="text-center">5</td><td class="text-right">50 000$</td></tr>
<tr><td class="text-center">2</td><td class="text-center">1</td><td class="text-center">15%-25%</td><td class="text-center">10</td><td class="text-right">100 000$</td></tr>
<tr><td class="text-center">3</td><td class="text-center">2</td><td class="text-center">25%-35%</td><td class="text-center">15</td><td class="text-right">150 000$</td></tr>
<tr><td class="text-center">4</td><td class="text-center">2</td><td class="text-center">35%-45%</td><td class="text-center">20</td><td class="text-right">200 000$</td></tr>
<tr><td class="text-center">5</td><td class="text-center">3</td><td class="text-center">45%-55%</td><td class="text-center">25</td><td class="text-right">250 000$</td></tr>
<tr><td class="text-center">6</td><td class="text-center">3</td><td class="text-center">55%-65%</td><td class="text-center">30</td><td class="text-right">300 000$</td></tr>
<tr><td class="text-center">7</td><td class="text-center">4</td><td class="text-center">65%-75%</td><td class="text-center">35</td><td class="text-right">350 000$</td></tr>
<tr><td class="text-center">8</td><td class="text-center">4</td><td class="text-center">75%-85%</td><td class="text-center">40</td><td class="text-right">400 000$</td></tr>
<tr><td class="text-center">9</td><td class="text-center">5</td><td class="text-center">85%-95%</td><td class="text-center">45</td><td class="text-right">450 000$</td></tr>
<tr><td class="text-center">10</td><td class="text-center">5</td><td class="text-center">100%</td><td class="text-center">50</td><td class="text-right">500 000$</td></tr>
</table>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>
<p class="strong text-justify" id="7.5">7.5. Секреты работы скаут-центров.</p>
<p class="text-justify">В любой команде, которая изучает любимый стиль одного и того же игрока, последовательность удаления неправильных стилей - одинаковая. Т.е. если в одной команде первое изучение дало результат, что стиль игрока точно не 10 man rugby, то первое изучение стиля этого же игрока в другой команде тоже даст результат, что стиль точно не скоростной.</p>
<p class="text-justify">Игрок, находящийся на изучении в скаут-центре, не может участвовать в сделках</p>
<p class="text-right text-size-3">[<a href="#0">к содержанию</a>]</p>',
    'title' => 'Базы команд',
];
